'use client';
/* eslint-disable react-hooks/set-state-in-effect */
import {useDeferredValue,useEffect,useMemo,useRef,useState} from 'react';
import type {Filters,Paper} from '../../lib/search';
import {accessLevel,addHistory,citation,defaults,excerpt,fields,fromParams,highlights,normalize,readLocal,safeUrl,search,suggestions,synonyms,toParams,writeLocal} from '../../lib/search';

const HISTORY='literature.search.history.v2', FAVORITES='literature.favorites.v2';
const fieldLabels:Record<string,string>={query:'关键词',field:'字段',category:'板块',journal:'期刊',method:'方法',access:'阅读状态',date:'收录日期',from:'起始年份',to:'结束年份',type:'类型',favorites:'仅收藏'};
const typeLabels:Record<string,string>={article:'期刊论文',preprint:'预印本',review:'综述',other:'其他'};
export function Highlight({text,terms}:{text:string;terms:string[]}){return <>{highlights(text,terms).map((p,i)=>p.hit?<mark key={i}>{p.text}</mark>:<span key={i}>{p.text}</span>)}</>}
export function Loading(){return <div className="library-loading" role="status"><p>正在载入文献索引…</p><div/><div/><div/></div>}
export default function SearchLibrary({papers,base=''}:{papers:Paper[];base?:string}){
 const [filters,setFilters]=useState<Filters>({...defaults});const [input,setInput]=useState('');const [history,setHistory]=useState<string[]>([]);const [favorites,setFavorites]=useState<string[]>([]);const [ready,setReady]=useState(false);const [notice,setNotice]=useState('');const [open,setOpen]=useState(false);const [active,setActive]=useState(-1);const [selected,setSelected]=useState<string[]>([]);const [question,setQuestion]=useState('');const [asked,setAsked]=useState('');
 const composing=useRef(false);const inputRef=useRef<HTMLInputElement>(null);const deferred=useDeferredValue(filters);const pending=deferred!==filters;
 useEffect(()=>{const f=fromParams(new URLSearchParams(location.search));setFilters(f);setInput(f.query);try{setHistory(readLocal(localStorage,HISTORY));setFavorites(readLocal(localStorage,FAVORITES))}catch{setNotice('浏览器存储不可用，历史和收藏仅在本次访问保留。')}setReady(true);
  const back=()=>{const f=fromParams(new URLSearchParams(location.search));setFilters(f);setInput(f.query)};const sync=()=>{try{setFavorites(readLocal(localStorage,FAVORITES));setHistory(readLocal(localStorage,HISTORY))}catch{}};window.addEventListener('popstate',back);window.addEventListener('storage',sync);return()=>{window.removeEventListener('popstate',back);window.removeEventListener('storage',sync)};
 },[]);
 useEffect(()=>{if(ready){const q=toParams(filters);window.history.replaceState(null,'',location.pathname+(q?'?'+q:''))}},[ready,filters]);
 const result=useMemo(()=>{try{return {...search(papers,deferred,favorites),error:''}}catch(e){return {items:[] as Paper[],all:[] as Paper[],total:0,pages:1,page:1,terms:[] as string[],error:e instanceof Error?e.message:'检索式无法解析。'}}},[papers,deferred,favorites]);
 function persist(key:string,values:string[]){try{if(writeLocal(localStorage,key,values))return}catch{}setNotice('浏览器未允许保存；历史和收藏仅在本次访问有效。')}
 useEffect(()=>{if(!ready||!filters.query.trim()||result.error)return;const timer=setTimeout(()=>{setHistory(prev=>{const next=addHistory(prev,toParams({...filters,page:1}));persist(HISTORY,next);return next})},1000);return()=>clearTimeout(timer)},[ready,filters,result.error]);
 const proposed=useMemo(()=>suggestions(input,papers),[input,papers]);
 const availableFavorites=favorites.filter(id=>papers.some(p=>p.id===id));
 function change<K extends keyof Filters>(key:K,value:Filters[K]){setFilters(f=>({...f,[key]:value,...(key==='page'?{}:{page:1})}));if(key==='query')setInput(String(value));setActive(-1)}
 function reset(){setFilters({...defaults});setInput('');setSelected([]);setOpen(false)}
 function toggle(id:string){setFavorites(prev=>{const next=prev.includes(id)?prev.filter(v=>v!==id):[...prev,id];persist(FAVORITES,next);return next})}
 function pick(value:string){change('query','"'+value.replaceAll('"','')+'"');setOpen(false);inputRef.current?.focus()}
 function restore(value:string){const f=fromParams(new URLSearchParams(value));setFilters(f);setInput(f.query);setOpen(false)}
 function download(list:Paper[],format:'bibtex'|'ris'){const blob=new Blob([list.map(p=>citation(p,format)).join('\n')],{type:format==='bibtex'?'application/x-bibtex;charset=utf-8':'application/x-research-info-systems;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`literature-${new Date().toISOString().slice(0,10)}.${format==='bibtex'?'bib':'ris'}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice(`已导出 ${list.length} 篇引用；缺失的作者、年份不会补写。`)}
 async function share(){try{await navigator.clipboard.writeText(location.href);setNotice('当前检索链接已复制，可分享筛选条件。')}catch{setNotice('请复制浏览器地址栏，当前筛选条件已保存在链接中。')}}
 const selections=result.all.filter(p=>selected.includes(p.id));
 const evidence=useMemo(()=>{if(!asked.trim())return [];const text=normalize(asked);const terms=[...new Set([...synonyms.filter(g=>g.some(v=>text.includes(v))).flat(),...(text.match(/[a-z0-9][a-z0-9.-]{2,}/g)??[]),...(text.match(/[\u3400-\u9fff]{2}/g)??[])])];if(!terms.length)return [];return papers.flatMap(p=>p.sections.map(s=>({p,s,score:terms.reduce((n,t)=>n+(normalize(s.text).includes(t)?1:0)+(normalize(p.material).includes(t)?2:0),0),terms}))).filter(v=>v.score>0).sort((a,b)=>b.score-a.score).slice(0,5)},[asked,papers]);
 const activeFilters=(Object.keys(fieldLabels) as (keyof Filters)[]).filter(k=>filters[k]!==defaults[k]);
 return <div className="research-library">
  <div className="library-title"><div><p className="eyebrow">LITERATURE EXPLORER</p><h1>文献检索</h1><p>在 {papers.length} 篇站内文献中，找到材料、方法与具体证据。</p></div><a href="#evidence-qa">证据问答 ↓</a></div>
  <div className="library-searchbox"><label htmlFor="library-query">关键词或高级检索式</label><div className="query-line"><span aria-hidden="true">⌕</span><input ref={inputRef} id="library-query" role="combobox" autoComplete="off" aria-autocomplete="list" aria-expanded={open&&proposed.length>0} aria-controls="query-options" aria-activedescendant={active>=0?`query-option-${active}`:undefined} aria-describedby="query-instructions" value={input} onFocus={()=>setOpen(true)} onBlur={e=>{if(!e.currentTarget.parentElement?.parentElement?.contains(e.relatedTarget as Node))setOpen(false)}} onCompositionStart={()=>{composing.current=true}} onCompositionEnd={e=>{composing.current=false;change('query',e.currentTarget.value)}} onChange={e=>{setInput(e.target.value);setOpen(true);setActive(-1);if(!composing.current)change('query',e.target.value)}} onKeyDown={e=>{if(e.nativeEvent.isComposing)return;if(e.key==='Escape'){setOpen(false);setActive(-1)}if(e.key==='ArrowDown'){e.preventDefault();setOpen(true);setActive(a=>Math.min(a+1,proposed.length-1))}if(e.key==='ArrowUp'){e.preventDefault();setActive(a=>Math.max(0,a-1))}if(e.key==='Enter'){e.preventDefault();if(open&&active>=0&&proposed[active])pick(proposed[active]);else setOpen(false)}}} placeholder={'例如：CVT AND (磁振子 OR superconductivity) NOT 薄膜'}/>{input&&<button type="button" onClick={()=>change('query','')} aria-label="清空关键词">×</button>}</div>
   {open&&proposed.length>0&&<ul id="query-options" role="listbox" aria-label="关键词联想" className="suggestion-list">{proposed.map((v,i)=><li key={v} role="option" id={`query-option-${i}`} aria-selected={active===i}><button tabIndex={-1} onMouseDown={e=>e.preventDefault()} onClick={()=>pick(v)}><Highlight text={v} terms={[normalize(input)]}/><span>填入检索</span></button></li>)}</ul>}
   <p id="query-instructions">空格默认为 AND；支持 OR、NOT、括号和双引号短语。优先级：NOT → AND → OR。中英文同义词自动扩展。</p>
  </div>
  <div className="library-toolbar"><button onClick={()=>change('favorites',!filters.favorites)} aria-pressed={filters.favorites}>☆ 我的收藏（{availableFavorites.length}）</button><button onClick={share}>分享检索</button><button onClick={reset}>清除全部条件</button><details className="history-menu"><summary>检索历史（{history.length}）</summary><div>{history.length?history.map(v=><button key={v} onClick={()=>restore(v)}>{fromParams(new URLSearchParams(v)).query}<small>{Object.entries(fromParams(new URLSearchParams(v))).filter(([k,val])=>k!=='query'&&val!==defaults[k as keyof Filters]).map(([k,val])=>(fieldLabels[k]||k)+': '+val).join(' · ')}</small></button>):<p>输入关键词后自动保存，点击可恢复整组筛选。</p>}<button disabled={!history.length} onClick={()=>{setHistory([]);persist(HISTORY,[])}}>清空历史记录</button></div></details></div>
  <div className="library-workspace"><aside className="library-filters" aria-label="文献筛选"><h2>缩小范围</h2>
   <label>检索字段<select value={filters.field} onChange={e=>change('field',e.target.value)}>{Object.entries(fields).map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label>
   {(['category','journal','method','date'] as const).map(k=><label key={k}>{fieldLabels[k]}<select value={filters[k]} onChange={e=>change(k,e.target.value)}><option value="">全部</option>{[...new Set(papers.map(p=>p[k]))].sort().map(v=><option key={v} value={v}>{v}</option>)}</select></label>)}
   <label>阅读状态<select value={filters.access} onChange={e=>change('access',e.target.value)}><option value="">全部</option><option value="full">全文精读</option><option value="si">补充材料精读</option><option value="abstract">摘要 / 受限</option></select></label>
   <fieldset><legend>发表年份</legend><div className="year-range"><label><span className="sr-only">起始年份</span><input type="number" min="1800" max="2200" placeholder="起始年" value={filters.from} onChange={e=>change('from',e.target.value)}/></label><span>—</span><label><span className="sr-only">结束年份</span><input type="number" min="1800" max="2200" placeholder="结束年" value={filters.to} onChange={e=>change('to',e.target.value)}/></label></div></fieldset>
   <label>文献类型<select value={filters.type} onChange={e=>change('type',e.target.value)}><option value="">全部</option>{Object.entries(typeLabels).map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label>
   <details><summary>高级字段语法</summary><p><code>title:&quot;spin chain&quot; AND NOT author:Liu</code></p><p>可用 title / author / abstract / keywords，以及中文字段名。保留 主题:、期刊:、方法:、全文:、日期: 语法。</p></details>
   <p className="data-note">“原始摘要”只搜索已收录的论文摘要；“简报分析”搜索本站解读。年份缺失的论文不进入年份范围结果。</p>
  </aside>
  <section className="library-results" aria-label="检索结果" aria-busy={pending||!ready}>
   <div className="results-heading"><p role="status" aria-live="polite">{pending?'正在更新…':`${result.total} 篇匹配`}<small> · 第 {result.page} / {result.pages} 页</small></p><label>排序<select value={filters.sort} onChange={e=>change('sort',e.target.value)}><option value="relevance">相关度</option><option value="newest">最新发表</option><option value="citations">被引量</option></select></label></div>
   {filters.sort==='citations'&&<p className="data-note">{papers.some(p=>p.citations!==null)?'按 Crossref 收录的引用次数降序（与其他数据库可能不同）；未收录的排在末尾，各篇标明统计日期。':'当前文献库尚未收录被引量；均标为“未收录”，暂按发表日期排序。'}</p>}
   {filters.field==='abstract'&&!papers.some(p=>p.abstract)&&<p className="data-note">当前历史条目未保存原始摘要，可切换到“简报分析”搜索已有解读。</p>}
   <div className="filter-chips">{activeFilters.map(k=><button key={k} onClick={()=>change(k,defaults[k])}>{fieldLabels[k]}：{k==='favorites'?'是':k==='field'?fields[String(filters[k])]:String(filters[k])} <span aria-hidden="true">×</span><span className="sr-only">移除此条件</span></button>)}</div>
   <div className="export-toolbar"><label><input type="checkbox" checked={result.items.length>0&&result.items.every(p=>selected.includes(p.id))} onChange={e=>setSelected(prev=>e.target.checked?[...new Set([...prev,...result.items.map(p=>p.id)])]:prev.filter(id=>!result.items.some(p=>p.id===id)))}/>选择本页</label><span>{selections.length?`已选 ${selections.length} 篇`:'导出全部匹配结果'}</span><button disabled={!result.total} onClick={()=>download(selections.length?selections:result.all,'bibtex')}>BibTeX ↓</button><button disabled={!result.total} onClick={()=>download(selections.length?selections:result.all,'ris')}>RIS ↓</button></div>
   {notice&&<p className="library-notice" role="status">{notice}<button onClick={()=>setNotice('')} aria-label="关闭提示">×</button></p>}
   {!ready?<Loading/>:result.error?<div className="library-empty" role="alert"><h2>请调整检索条件</h2><p>{result.error}</p><button onClick={()=>change('query','CVT OR Flux')}>试用 CVT OR Flux</button></div>:!result.total?<div className="library-empty"><span aria-hidden="true">⌕</span><h2>{filters.favorites?'收藏中没有匹配文献':'没有找到匹配文献'}</h2><p>可减少条件，将 AND 改为 OR，或换用材料名称和中英文同义词。</p>{filters.field==='abstract'&&<button onClick={()=>change('field','summary')}>改搜简报分析</button>}<button onClick={reset}>清除筛选，查看全部</button><div>{['Flux','CVT','超导','重费米子'].map(q=><button key={q} onClick={()=>{setFilters({...defaults,query:q});setInput(q)}}>{q}</button>)}</div></div>:<div className={pending?'result-list pending':'result-list'}>{result.items.map(p=><article key={p.id} className="literature-result"><div className="result-meta"><label><input type="checkbox" aria-label={`选择 ${p.title}`} checked={selected.includes(p.id)} onChange={()=>setSelected(prev=>prev.includes(p.id)?prev.filter(id=>id!==p.id):[...prev,p.id])}/>{p.year??'年份未收录'} · {typeLabels[p.type]??p.type}</label><span>{p.category}</span><button aria-pressed={favorites.includes(p.id)} aria-label={`${favorites.includes(p.id)?'取消收藏':'收藏'} ${p.title}`} onClick={()=>toggle(p.id)}>{favorites.includes(p.id)?'★ 已收藏':'☆ 收藏'}</button></div>
    <h2><a href={base+p.reportUrl}><Highlight text={p.title} terms={result.terms}/></a></h2><p className="result-authors"><Highlight text={p.authors||'作者未收录'} terms={result.terms}/></p><p className="result-source"><Highlight text={p.journal} terms={result.terms}/> · {p.published||'发表日期未收录'}<span>收录于 {p.date}</span></p>
    <div className="result-keywords">{[p.material,...p.tags].slice(0,8).map((tag,i)=><button key={i} title="按此关键词搜索" onClick={()=>pick(tag)}><Highlight text={tag} terms={result.terms}/></button>)}</div>
    <p className="result-excerpt"><b>{p.abstract&&filters.field==='abstract'?'原始摘要':'简报分析'}：</b><Highlight text={excerpt(p.abstract&&filters.field==='abstract'?p.abstract:p.summary,result.terms)} terms={result.terms}/></p>
    <div className="result-quality"><span>{accessLevel(p)==='full'?'全文精读':accessLevel(p)==='si'?'补充材料精读':'摘要 / 访问受限'}</span><span>Crossref 被引量：{p.citations===null?'未收录':p.citations}{p.citationDate?' · '+p.citationDate:''}</span></div>
    <details className="result-detail"><summary>展开研究与阅读建议</summary><p><b>生长 / 方法：</b>{p.method||'未收录'}</p><p><b>阅读范围：</b>{p.access}</p>{p.readingGuide&&<><p><b>先读：</b>{p.readingGuide.first}</p><p><b>判断重点：</b>{p.readingGuide.focus}</p><p><b>下一步：</b>{p.readingGuide.next}</p></>}{p.abstract&&<p><b>原始摘要：</b><Highlight text={p.abstract} terms={result.terms}/></p>}</details>
    <div className="result-actions"><a href={base+p.reportUrl}>阅读详解 →</a><a href={safeUrl(p.source)} target="_blank" rel="noreferrer">原文 ↗</a><button onClick={()=>download([p],'bibtex')}>BibTeX</button><button onClick={()=>download([p],'ris')}>RIS</button></div>
   </article>)}</div>}
   <nav className="library-pagination" aria-label="结果分页"><button disabled={result.page<=1} onClick={()=>change('page',result.page-1)}>← 上一页</button>{Array.from({length:result.pages},(_,i)=>i+1).filter(n=>n===1||n===result.pages||Math.abs(n-result.page)<2).map((n,i,arr)=><span key={n}>{i>0&&n-arr[i-1]>1&&<span>…</span>}<button aria-current={n===result.page?'page':undefined} onClick={()=>change('page',n)}>{n}</button></span>)}<button disabled={result.page>=result.pages} onClick={()=>change('page',result.page+1)}>下一页 →</button><label>每页<select value={filters.size} onChange={e=>change('size',+e.target.value)}>{[10,20,50].map(n=><option key={n}>{n}</option>)}</select></label></nav>
  </section></div>
  <details id="evidence-qa" className="library-evidence"><summary>证据问答：追问生长参数、测量条件和结论依据</summary><p>从站内已整理段落检索并逐条列出来源；这是证据摘录，不是外部模型生成的答案。</p><form onSubmit={e=>{e.preventDefault();setAsked(question)}}><label htmlFor="research-question">具体科研问题</label><textarea id="research-question" rows={3} value={question} onChange={e=>setQuestion(e.target.value)} placeholder="例如：FePS3 的 CVT 生长温度和输运剂用量？"/><button disabled={!question.trim()}>查找证据</button></form>{asked&&<div aria-live="polite"><h2>与“{asked}”相关的证据</h2>{evidence.length?evidence.map((v,i)=><article key={v.p.id+v.s.title}><h3>{i+1}. {v.p.material} · {v.s.title}</h3><p><Highlight text={excerpt(v.s.text,v.terms,600)} terms={v.terms}/></p><a href={base+v.p.reportUrl}>查看上下文 →</a> · <a href={safeUrl(v.p.source)}>原文 ↗</a></article>):<p>暂无足够证据，请加入材料名、方法或参数名称。</p>}</div>}</details>
  <p className="library-footnote">检索范围为本站已收录文献。历史与收藏保存在当前浏览器，Sites 与 GitHub Pages 各自保存；不跨设备同步。</p>
 </div>;
}
