/* eslint-disable @next/next/no-html-link-for-pages */
import type { Metadata } from 'next';
import report from '../../../content/reports/2026-09-02.json';

export const metadata: Metadata = {title:'2026-09-02 简报｜每日文献简报',description:report.headline};
const ids=report.papers.map((_,i)=>`paper-${i+1}`);

function GrowthMap(){return <figure className="data-figure"><figcaption><b>图 1｜本期镍酸盐生长窗口对照</b><span>根据论文方法原创重绘，并非论文原图</span></figcaption><div className="growth-map"><article><i>K₂CO₃ Flux</i><strong>La₃Ni₂O₇</strong><b>常压 · 1000–1050 °C · 72 h</b><p>溶质:Flux=1:15；O₂ 500 °C/5 d</p></article><article><i>SrCl₂–KCl Flux</i><strong>La₂SrNi₂O₇−δ</strong><b>3 GPa · 1400 °C</b><p>SrO₂ 控制氧活度；直键仍未带来超导</p></article><article><i>HPHT + KClO₄</i><strong>Sm₄Ni₃O₁₀−δ</strong><b>3.25 GPa · 1400 °C</b><p>窗口窄；Pbca 倾转与氧亏缺需联动统计</p></article></div><p className="figure-analysis"><b>怎样读这张图：</b>三种路线并非只比较压力。它们同时改变熔盐化学、氧活度、离子尺寸和轨道填充。La₂SrNi₂O₇−δ 与 Sm₄Ni₃O₁₀−δ 的负结果说明“更直的 Ni–O–Ni 键”或“更小稀土离子”都不能单独预测超导；下一轮实验应把氧含量与单晶结构作为每个输运样品的伴随变量。</p></figure>}
function PressureFigure(){return <figure className="data-figure dark-data"><figcaption><b>图 2｜La₃Ni₂O₇ 结构转变与光学金属化</b><span>依据公开作者稿数值原创重绘，并非论文原图</span></figcaption><div className="pressure-chart"><div className="phase-axis"><span>0.4 GPa</span><span>6 GPa</span><span>15.25 GPa</span><span>16.9 GPa</span></div><div className="phase-bar"><i>倾转相</i><i>相共存区</i><i>无倾转相</i></div><div className="plasma-row"><span>等离子频率</span><b>3450 cm⁻¹</b><em>→ 近 9.3 倍 →</em><b>32000 cm⁻¹</b></div><div className="temp-row"><span>温度路径</span><b>约 400 K 开始</b><em>→</em><b>约 544 K 完成</b></div></div><p className="figure-analysis"><b>证据意义：</b>结构声子消失和 Drude 响应增强在压力、温度两条路径上同步，是本文最强证据。但等离子频率平方与 n/m* 成正比，所以“载流子密度增加近两个数量级”还依赖有效质量变化较小这一假设；它不能替代 Hall 测量。</p></figure>}
function DeviceFigure(){return <figure className="data-figure"><figcaption><b>图 3｜GaAs/GaAsP 外延堆栈与低温极化</b><span>根据 Methods 原创重绘，并非论文原图</span></figcaption><div className="device-stack"><div className="layers"><i>30 × [3.8 nm GaAs / 2.8 nm GaAs₀.₆₅P₀.₃₅]</i><i>2.5 μm GaAs₀.₆₅P₀.₃₅ 终端层</i><i>每步 500 nm、P 增量 2.5% 的渐变缓冲</i><i>p-GaAs(100) · Zn 5×10¹⁸ cm⁻³</i></div><div className="polarization"><span>295 K<b>91.2%</b></span><i>冷却抑制热化输运去极化</i><span>195 K<b>95.0%</b></span><small>77 K 不再明显提升</small></div></div><p className="figure-analysis"><b>证据意义：</b>同一阴极的冷却—回温可逆性排除了永久表面损伤这一解释；195 K 后饱和说明仍有高能热电子弛豫等通道。复现应同时报告 HRXRD 松弛、NEA 激活循环、真实阴极温度和 Sherman 函数，而非只报告峰值极化。</p></figure>}

export default function Report(){const full=report.papers.filter(p=>p.access.includes('全文精读')).length;return <main className="report-page"><header className="site-header"><a className="brand" href="/"><span className="brand-mark">文</span><span>每日文献简报</span></a><nav><a className="active" href="/reports/2026-09-02">今日简报</a><a href="/#topics">研究板块</a><a href="/archive">往期归档</a><a href="/search">智能检索</a></nav><div className="live-chip"><span/> 每日 08:00 更新</div></header>
<div className="report-hero"><div><p className="eyebrow">DAILY REPORT · ISSUE 008</p><h1>每日文献简报</h1><p>2026 年 9 月 2 日 · 北京时间</p></div><div className="report-summary"><b>今日判断</b><p>{report.headline}</p><div><span>{report.papers.length} 篇入选</span><span>{full} 篇全文精读</span><span>5 个研究板块</span></div></div></div>
<div className="report-layout"><aside className="report-toc"><p>本期目录</p>{report.papers.map((p,i)=><a key={p.title} href={`#${ids[i]}`}>{String(i+1).padStart(2,'0')} · {p.material}</a>)}<a href="#figures">定量图解</a><a href="#compare">汇总对比</a><a href="#search">检索记录</a></aside><article className="report-content">
<section className="report-lede"><p className="eyebrow">TODAY&apos;S SIGNAL</p><h2>今日要点与访问说明</h2><p>{report.hotspot}</p><ol><li><b>不是所有“全文不可访问”都能由 VPN 解决。</b>USbTe 页面本身尚未发布正文；Nature Physics 需要机构认证但当前网页端会话未登录；Ti–Al 未找到公开稿。</li><li><b>5 篇 PRB 已通过作者公开稿补全。</b>正式 DOI 仍作为主引用，公开稿只用于读取正文、方法与图表，并在每篇中标明版本关系。</li><li><b>图片改为定量原创重绘。</b>避免复制付费论文图片，同时保留坐标、条件、数值、证据意义与模型边界。</li></ol></section>
<section id="figures"><GrowthMap/><PressureFigure/><DeviceFigure/></section>
{report.papers.map((p,i)=><section className="paper-detail" id={ids[i]} key={p.title}><div className="paper-kicker"><span>{String(i+1).padStart(2,'0')} · {p.category}</span><b>{p.access.includes('全文精读')?'全文精读':'访问受限'} · 推荐 {p.rating}</b></div><h2>{p.material}：{p.title}</h2><div className="tag-row">{p.tags.map(t=><span key={t}>{t}</span>)}</div><div className="meta-grid"><div className="meta-item"><span>来源</span><b>{p.journal}</b></div><div className="meta-item"><span>日期</span><b>{p.date}</b></div><div className="meta-item"><span>生长 / 方法</span><b>{p.method}</b></div><div className="meta-item"><span>作者</span><b>{p.authors}</b></div></div><p className="links"><a href={p.doi}>DOI / 正式条目 ↗</a><a href={p.fullText}>公开全文 / 出版社页 ↗</a></p>{'versionNote' in p&&<p className="version-note"><b>版本与访问：</b>{p.versionNote}</p>}{p.sections.map(s=><div key={s.title}><h3>{s.title}</h3><p>{s.text}</p></div>)}<div className="reading-guide"><span>{p.readingGuide.priority}</span><h3>这篇论文怎么读</h3><p><b>先读：</b>{p.readingGuide.first}</p><p><b>重点：</b>{p.readingGuide.focus}</p><p><b>下一步：</b>{p.readingGuide.next}</p></div></section>)}
<section className="comparison" id="compare"><p className="eyebrow">COMPARISON</p><h2>本期汇总</h2><div className="table-wrap"><table><thead><tr><th>板块</th><th>材料</th><th>生长 / 方法</th><th>证据状态</th><th>推荐</th></tr></thead><tbody>{report.papers.map(p=><tr key={p.title}><td>{p.category}</td><td>{p.material}</td><td>{p.method}</td><td>{p.access}</td><td>{p.rating}</td></tr>)}</tbody></table></div></section>
<section className="search-note" id="search"><p className="eyebrow">SEARCH LOG</p><h2>检索、访问与去重</h2><p><b>时间窗：</b>{report.searchWindow}</p><p><b>检索范围：</b>{report.searchTerms.join('；')}。</p><p><b>访问结果：</b>10 篇全文精读；其中 5 篇 PRB 由正式 DOI 与同作者公开稿建立版本关系。USbTe 为出版社尚无正文的提前发布版，Nature Physics Perspective 的机构认证未完成，Ti–Al PRB 未找到公开稿，三者不补写不可见参数。</p><p><b>后续新增来源：</b>每日固定检索 Crystal Growth &amp; Design 和 Journal of Crystal Growth，并继续覆盖 APS/PR 全系列、Nature/Science 系列、Advanced Materials/AFM、Nano Letters、ACS Nano、JACS、Chemistry of Materials 与 npj Quantum Materials。</p></section>
</article></div></main>}
