/* eslint-disable @next/next/no-html-link-for-pages, @next/next/no-img-element */
import type {Metadata} from 'next';
import report from '../../../content/reports/2026-09-17.json';

export const metadata:Metadata={title:'2026-09-17 简报｜每日文献简报',description:report.headline};

const figures:Record<string,{src:string;title:string;caption:string}>= {
  'Electrically controllable superconducting memory effect in UTe₂':{src:'/reports/2026-09-17/ute2-memory.svg',title:'原创图解 1｜UTe₂电流记忆的场温窗口',caption:'据Nature图1–4的文字与数值重绘。横轴是B∥b的近似场窗口，7–20 T为不同样品的典型范围，绝非逐点临界场曲线；温度窗口另列。最关键的对照是30 T纯SC2与0.65 K附近效应消失。来源：https://www.nature.com/articles/s41586-026-11015-3 ，开放获取CC BY 4.0；本站为原创图解。'},
  'Complex magnetic properties of EuAgAs single crystals':{src:'/reports/2026-09-17/euagas-growth.svg',title:'原创图解 2｜EuAgAs助熔剂生长温程',caption:'按arXiv:2609.18354的Methods数值重绘，不是炉温原始记录。1100°C保温24 h后250 h降至700°C，平均约1.6°C/h；离心与汞齐除Bi仍会留少量残Bi。来源：https://arxiv.org/abs/2609.18354 ，本站原创图解。'},
  'Magnetically coupled charge-transport crossover and giant negative magnetoresistance in iodine-incorporated Cr₂Se₃':{src:'/reports/2026-09-17/cr2se3-mr.svg',title:'原创图解 3｜Cr₂Se₃含碘晶体的负磁阻',caption:'据arXiv:2609.17945给出的12 T三温度MR数字重绘；横条长度只表达幅值，不是连续MR(B)曲线。25 K的−78%大于5 K的−53%，提示磁序以外的载流子/散射通道也应考量。来源：https://arxiv.org/abs/2609.17945 ，本站原创图解。'}
};

export default function Report(){
 const full=report.papers.filter(p=>p.access.includes('全文精读')).length;
 const counts=report.papers.reduce<Record<string,number>>((m,p)=>(m[p.category]=(m[p.category]||0)+1,m),{});
 return <main className="report-page">
 <header className="site-header"><a className="brand" href="/"><span className="brand-mark">文</span><span>每日文献简报</span></a><nav aria-label="主导航"><a className="active" href="/reports/2026-09-17">今日简报</a><a href="/materials">材料时间线</a><a href="/search">智能检索</a><a href="/weekly">本周趋势</a><a href="/workspace">我的研究</a><a href="/archive">归档</a></nav><div className="live-chip"><span/> 每日 10:00 更新</div></header>
 <div className="report-hero"><div><p className="eyebrow">DAILY REPORT · ISSUE 023</p><h1>每日文献简报</h1><p>2026 年 9 月 17 日 · 北京时间</p></div><div className="report-summary"><b>今日判断</b><p>{report.headline}</p><div><span>{report.papers.length} 篇入选</span><span>{full} 篇全文精读</span><span>正式期刊 3 篇</span></div></div></div>
 <div className="report-layout"><aside className="report-toc"><p>本期目录</p>{report.papers.map((p,i)=><a key={p.title} href={'#paper-'+(i+1)}>{String(i+1).padStart(2,'0')} · {p.material.slice(0,14)}</a>)}<a href="#compare">板块统计</a><a href="#search-log">检索日志</a></aside><article className="report-content">
 <section className="report-lede"><p className="eyebrow">TODAY&apos;S SIGNAL</p><h2>今日要点与访问边界</h2><p>{report.hotspot}</p><ol><li><b>正式期刊与预印本：</b>Nature 1篇（前日漏收补录）、Nano Letters当天上线2篇，另有10篇arXiv新稿。</li><li><b>阅读等级：</b>4篇全文精读、7篇PDF正文核查、2篇只基于正式摘要；后两类不冒称精读。</li><li><b>实验优先：</b>UTe₂电流记忆、EuAgAs的Bi Flux和Cr₂Se₃的I辅助CVT给出最直接的生长—物性链。</li><li><b>图解合规：</b>三张均由本站根据公开论文数字原创重绘，标明来源与证据边界。</li></ol></section>
 {report.papers.map((p,i)=>{const fig=figures[p.title];return <section className="paper-detail" id={'paper-'+(i+1)} key={p.title}><div className="paper-kicker"><span>{String(i+1).padStart(2,'0')} · {p.category}</span><b>{p.access.includes('全文精读')?'全文精读':p.access.includes('正文核查')?'正文核查':'摘要级'} · 推荐 {p.rating}</b></div><h2>{p.material}｜{p.title}</h2><div className="tag-row">{p.tags.map(t=><span key={t}>{t}</span>)}</div><div className="meta-grid"><div className="meta-item"><span>来源</span><b>{p.journal}</b></div><div className="meta-item"><span>上线日期</span><b>{p.date}</b></div><div className="meta-item"><span>生长 / 方法</span><b>{p.method}</b></div><div className="meta-item"><span>作者</span><b>{p.authors}</b></div><div className="meta-item institution-item"><span>主要单位</span><b>{p.institutions}</b></div></div><p className="links"><a href={p.doi}>DOI / 原文 ↗</a></p><p className="version-note"><b>版本与阅读范围：</b>{p.versionNote} {p.access}</p><div className="paper-conclusion"><span>CONCLUSION</span><h3>这篇论文讲了什么故事</h3><p>{p.conclusion}</p></div>{fig&&<figure className="data-figure"><figcaption><b>{fig.title}</b><span>根据公开Methods与正文数值重绘，并非论文原图</span></figcaption><img className="report-figure-image" src={fig.src} alt={fig.title}/><p className="figure-analysis"><b>图解分析：</b>{fig.caption}</p></figure>}{p.sections.map(s=><div key={s.title}><h3>{s.title}</h3>{s.text.split('\n\n').map((part,j)=><p key={j}>{part}</p>)}</div>)}<div className="reading-guide"><span>{p.readingGuide.priority}</span><h3>本篇专属阅读路径</h3><p><b>先读：</b>{p.readingGuide.first}</p><p><b>重点：</b>{p.readingGuide.focus}</p><p><b>下一步：</b>{p.readingGuide.next}</p></div></section>})}
 <section className="comparison" id="compare"><p className="eyebrow">TODAY AT A GLANCE</p><h2>板块与全文状态</h2><div className="table-wrap"><table><thead><tr><th>研究板块</th><th>篇数</th></tr></thead><tbody>{Object.entries(counts).map(([k,v])=><tr key={k}><td>{k}</td><td>{v}</td></tr>)}</tbody></table></div><p>正式期刊3篇；arXiv独立新收录10篇；全文精读4篇；正文核查7篇；仅摘要2篇。各篇生长方法、关键物性与推荐等级见上方分篇标题和结论。</p></section>
 <section className="search-note" id="search-log"><p className="eyebrow">SEARCH LOG</p><h2>逐轨检索、访问与去重记录</h2><p><b>时间窗：</b>{report.searchWindow}</p>{report.searchTerms.map(x=><p key={x}>{x}</p>)}</section>
 </article></div></main>;
}
