/* eslint-disable @next/next/no-html-link-for-pages */
import type { Metadata } from 'next';
import report from '../../../content/reports/2026-09-03.json';

export const metadata: Metadata = {title:'2026-09-03 简报｜每日文献简报',description:report.headline};
const ids=report.papers.map((_,i)=>`paper-${i+1}`);

function GrowthMap(){return <figure className="data-figure"><figcaption><b>图 1｜两类单晶生长与缺陷/功能响应</b><span>依据 Methods 数值原创重绘，并非论文原图</span></figcaption><div className="growth-map"><article><i>浮区 vs Verneuil</i><strong>Cr₂O₃</strong><b>E1 强度相差约 100 倍</b><p>低空位样 spin-flop 更尖锐；64→27 cm⁻¹ @ 约 6 T</p></article><article><i>Sn Flux · 1:6:20</i><strong>YMn₆Sn₆</strong><b>1175 °C/1 d → 600 °C</b><p>6 °C/h；离心分离；室温体磁致伸缩 &gt;400 ppm</p></article><article><i>self-flux + O₂</i><strong>Tl₂Ba₂CuO₆</strong><b>450 °C · 14–18 h</b><p>0.001–1 bar O₂；Tc 14–45 K；转变宽约 1 K</p></article></div><p className="figure-analysis"><b>怎样读这张图：</b>三个结果共同说明“物性”必须绑定样品历史。Cr₂O₃ 的空位差成为量子缺陷信号，YMn₆Sn₆ 的降温窗口决定可用单晶，Tl2201 的氧退火把同一母相推到不同过掺杂状态。复现时应记录炉次、晶体编号与最终测量样品的一一对应，而不是只引用一种通用生长法。</p></figure>}
function PressureFigure(){return <figure className="data-figure dark-data"><figcaption><b>图 2｜YMn₆Sn₆ 的交换磁致伸缩证据链</b><span>根据论文定量结果原创重绘，并非论文原图</span></figcaption><div className="pressure-chart"><div className="phase-axis"><span>0 T</span><span>螺旋/多相区</span><span>接近极化</span><span>9 T</span></div><div className="phase-bar"><i>非共线自旋</i><i>交换竞争驱动重构</i><i>近共线态</i></div><div className="plasma-row"><span>体应变量级</span><b>低温约 −1200 ppm</b><em>随温度减弱</em><b>室温仍 &gt;400 ppm</b></div><div className="temp-row"><span>可靠性</span><b>应变片</b><em>↔ 交叉验证 ↔</em><b>电容膨胀计</b></div></div><p className="figure-analysis"><b>证据意义：</b>大应变、近无滞后和磁相边界同步，再加两种测量方法一致，支持交换重构而非普通畴壁运动。DFT 对 SOC-ME 与 Exchange-ME 的分离是机制模型；真正的下一步应是原位高场衍射直接看到晶格和螺旋波矢同步变化。</p></figure>}
function DeviceFigure(){return <figure className="data-figure"><figcaption><b>图 3｜金属覆盖 InAs 量子阱的两类二维频率</b><span>依据量子振荡数据原创重绘，并非论文原图</span></figcaption><div className="device-stack"><div className="layers"><i>Al / Sn：界面支 25–27 T</i><i>V / Nb / Ta / Re：界面支 11.0–13.4 T</i><i>InGaAs 界面积累层（二维角依赖）</i><i>埋藏 InAs 量子阱：所有样品约 5.2 T</i></div><div className="polarization"><span>深阱密度<b>2.5×10¹¹ cm⁻²</b></span><i>质量与 g 在 10% 内不变</i><span>耦合上限<b>2–4 meV</b></span><small>由量子寿命约束，并非直接测量</small></div></div><p className="figure-analysis"><b>证据意义：</b>金属没有抹掉深阱振荡，却新增一个随 1/cosθ 的界面支，说明器件至少含两条半导体通道。Al/Sn 与 d 带金属形成两类占据；这种分类与功函数并不一一对应，界面轨道和化学仍需独立表征。</p></figure>}

export default function Report(){const full=report.papers.filter(p=>p.access.includes('全文精读')).length;return <main className="report-page"><header className="site-header"><a className="brand" href="/"><span className="brand-mark">文</span><span>每日文献简报</span></a><nav><a className="active" href="/reports/2026-09-03">今日简报</a><a href="/#topics">研究板块</a><a href="/archive">往期归档</a><a href="/search">智能检索</a></nav><div className="live-chip"><span/> 每日 08:00 更新</div></header>
<div className="report-hero"><div><p className="eyebrow">DAILY REPORT · ISSUE 009</p><h1>每日文献简报</h1><p>2026 年 9 月 3 日 · 北京时间</p></div><div className="report-summary"><b>今日判断</b><p>{report.headline}</p><div><span>{report.papers.length} 篇入选</span><span>{full} 篇全文精读</span><span>5 个研究板块</span></div></div></div>
<div className="report-layout"><aside className="report-toc"><p>本期目录</p>{report.papers.map((p,i)=><a key={p.title} href={`#${ids[i]}`}>{String(i+1).padStart(2,'0')} · {p.material}</a>)}<a href="#figures">定量图解</a><a href="#compare">汇总对比</a><a href="#search">检索记录</a></aside><article className="report-content">
<section className="report-lede"><p className="eyebrow">TODAY&apos;S SIGNAL</p><h2>今日要点与访问说明</h2><p>{report.hotspot}</p><ol><li><b>正式期刊优先检索，今天没有合格新增。</b>APS、Nature/Science、Wiley、ACS、Crystal Growth &amp; Design 与 Journal of Crystal Growth 均核查；没有用更早论文填充。</li><li><b>北京时间日期与 arXiv 日期分开记录。</b>本期条目来自 9 月 2 日 20:00 EDT 的新提交批次，在北京时间 9 月 3 日 08:00 后可见，因此计入今天。</li><li><b>10 篇全部阅读公开全文。</b>方法参数缺失处逐项指出；三张图为依据正文数值原创重绘，不复制受保护图形。</li></ol></section>
<section id="figures"><GrowthMap/><PressureFigure/><DeviceFigure/></section>
{report.papers.map((p,i)=><section className="paper-detail" id={ids[i]} key={p.title}><div className="paper-kicker"><span>{String(i+1).padStart(2,'0')} · {p.category}</span><b>{p.access.includes('全文精读')?'全文精读':'访问受限'} · 推荐 {p.rating}</b></div><h2>{p.material}：{p.title}</h2><div className="tag-row">{p.tags.map(t=><span key={t}>{t}</span>)}</div><div className="meta-grid"><div className="meta-item"><span>来源</span><b>{p.journal}</b></div><div className="meta-item"><span>日期</span><b>{p.date}</b></div><div className="meta-item"><span>生长 / 方法</span><b>{p.method}</b></div><div className="meta-item"><span>作者</span><b>{p.authors}</b></div></div><p className="links"><a href={p.doi}>DOI / 正式条目 ↗</a><a href={p.fullText}>公开全文 / 出版社页 ↗</a></p>{'versionNote' in p&&<p className="version-note"><b>版本与访问：</b>{p.versionNote}</p>}{p.sections.map(s=><div key={s.title}><h3>{s.title}</h3><p>{s.text}</p></div>)}<div className="reading-guide"><span>{p.readingGuide.priority}</span><h3>这篇论文怎么读</h3><p><b>先读：</b>{p.readingGuide.first}</p><p><b>重点：</b>{p.readingGuide.focus}</p><p><b>下一步：</b>{p.readingGuide.next}</p></div></section>)}
<section className="comparison" id="compare"><p className="eyebrow">COMPARISON</p><h2>本期汇总</h2><div className="table-wrap"><table><thead><tr><th>板块</th><th>材料</th><th>生长 / 方法</th><th>证据状态</th><th>推荐</th></tr></thead><tbody>{report.papers.map(p=><tr key={p.title}><td>{p.category}</td><td>{p.material}</td><td>{p.method}</td><td>{p.access}</td><td>{p.rating}</td></tr>)}</tbody></table></div></section>
<section className="search-note" id="search"><p className="eyebrow">SEARCH LOG</p><h2>检索、访问与去重</h2><p><b>时间窗：</b>{report.searchWindow}</p><p><b>检索范围：</b>{report.searchTerms.join('；')}。</p><p><b>访问结果：</b>10 篇均取得并阅读 arXiv PDF，阅读范围覆盖正文、方法或附录及图注；当天正式期刊检索结果为 0 篇合格新增。</p><p><b>后续新增来源：</b>每日固定检索 Crystal Growth &amp; Design 和 Journal of Crystal Growth，并继续覆盖 APS/PR 全系列、Nature/Science 系列、Advanced Materials/AFM、Nano Letters、ACS Nano、JACS、Chemistry of Materials 与 npj Quantum Materials。</p></section>
</article></div></main>}

