/* eslint-disable @next/next/no-html-link-for-pages, @next/next/no-img-element */
import type {Metadata} from 'next';
import report from '../../../content/reports/2026-09-23.json';

export const metadata:Metadata={title:'2026-09-23 简报｜每日文献简报',description:report.headline};
const figures:Record<string,{src:string;title:string;caption:string}>={
 '5DSTEM of Liquid-Phase Nanocrystal Growth Bridges Ensemble Kinetics and Nanoscale Dynamics':{src:'/reports/2026-09-23/au-5dstem.svg',title:'原创图解 1｜Au纳米晶：群体动力学中的两条微观路径',caption:'连续生长颗粒面积近线性增加，R²≈0.97；并合颗粒出现面积突跳但前后仍为表面反应受限。取向突变与表面至内部拉伸应变支持取向附着，不能排除电子束和液池窗口的扰动。'},
 'Different reconstruction pathways toward superconductivity in TaRhTe4 and TaIrTe4 Weyl semimetals':{src:'/reports/2026-09-23/tarhte4-pressure.svg',title:'原创图解 2｜TaRhTe₄：宽压力重构区通向超导',caption:'约20 GPa开始晶格渐进畸变和超导下降；63.3 GPa以上零电阻，65.2 GPa的Tc,onset≈2.6 K。Hall趋零和MR坍缩说明多带重构，但不等于高压Weyl拓扑已证实。'},
 'The observation of bulk superconductivity in Rhombohedral ReO3 under pressure':{src:'/reports/2026-09-23/reo3-dome.svg',title:'原创图解 3｜ReO₃：菱方结构中的体超导窗口',caption:'压力把Pm-3m/Im-3推向R-3c并在28 GPa给Tc,onset≈17.5 K；35–40 GPa以上进一步降对称后体超导退化。相边界仍受压媒和低温压力漂移影响。'}
};
export default function Report(){
 const full=report.papers.filter(p=>p.access.includes('全文精读')).length;
 const formal=report.papers.filter(p=>p.tags.includes('正式期刊')).length;
 const counts=report.papers.reduce<Record<string,number>>((m,p)=>(m[p.category]=(m[p.category]||0)+1,m),{});
 return <main className="report-page"><header className="site-header"><a className="brand" href="/"><span className="brand-mark">文</span><span>每日文献简报</span></a><nav aria-label="主导航"><a className="active" href="/reports/2026-09-23">今日简报</a><a href="/materials">材料时间线</a><a href="/search">智能检索</a><a href="/weekly">本周趋势</a><a href="/workspace">我的研究</a><a href="/archive">归档</a></nav><div className="live-chip"><span/> 每日更新</div></header>
 <div className="report-hero"><div><p className="eyebrow">DAILY REPORT · ISSUE 029</p><h1>每日文献简报</h1><p>2026 年 9 月 23 日 · 北京时间</p></div><div className="report-summary"><b>今日判断</b><p>{report.headline}</p><div><span>{report.papers.length} 篇入选</span><span>{full} 篇全文精读</span><span>正式期刊 {formal} 篇</span></div></div></div>
 <div className="report-layout"><aside className="report-toc"><p>本期目录</p>{report.papers.map((p,i)=><a key={p.title} href={'#paper-'+(i+1)}>{String(i+1).padStart(2,'0')} · {p.material.slice(0,16)}</a>)}<a href="#compare">汇总统计</a><a href="#search-log">检索日志</a></aside><article className="report-content">
 <section className="report-lede"><p className="eyebrow">TODAY&apos;S SIGNAL</p><h2>今日要点与访问边界</h2><p>{report.hotspot}</p><ol><li><b>出版社优先：</b>3篇当天正式期刊条目进入摘要级整理；APS、Science、Crystal Growth &amp; Design和Journal of Crystal Growth均为零纳入。</li><li><b>公开全文：</b>8篇arXiv实验论文读取正文、Methods和图注；旧论文今日补传arXiv的Sr₂IrO₄已按版本关系排除。</li><li><b>证据链：</b>每篇先给独立Conclusion，再区分直接观察、模型拟合、作者推断和本站判断；未知参数不补写。</li><li><b>原创图解：</b>三张图重绘Au生长路径、TaRhTe₄压力重构和ReO₃结构—超导窗口，并写清不能证明的内容。</li></ol></section>
 {report.papers.map((p,i)=>{const fig=figures[p.title];return <section className="paper-detail" id={'paper-'+(i+1)} key={p.title}><div className="paper-kicker"><span>{String(i+1).padStart(2,'0')} · {p.category}</span><b>{p.access.includes('全文精读')?'全文精读':'摘要级'} · 推荐 {p.rating}</b></div><h2>{p.material}｜{p.title}</h2><div className="tag-row">{p.tags.map(t=><span key={t}>{t}</span>)}</div><div className="meta-grid"><div className="meta-item"><span>来源</span><b>{p.journal}</b></div><div className="meta-item"><span>日期</span><b>{p.date}</b></div><div className="meta-item"><span>生长 / 方法</span><b>{p.method}</b></div><div className="meta-item"><span>作者</span><b>{p.authors}</b></div><div className="meta-item institution-item"><span>主要单位</span><b>{p.institutions}</b></div></div><p className="links"><a href={p.doi}>DOI / arXiv ↗</a>{p.fullText&&p.fullText!==p.doi&&<a href={p.fullText}> 公开全文 ↗</a>}</p><p className="version-note"><b>版本与阅读范围：</b>{p.versionNote} {p.access}</p><div className="paper-conclusion"><span>CONCLUSION</span><h3>这篇论文讲了什么故事</h3><p>{p.conclusion}</p></div>{fig&&<figure className="data-figure"><figcaption><b>{fig.title}</b><span>根据公开正文数值重绘，并非论文原图</span></figcaption><img className="report-figure-image" src={fig.src} alt={fig.title}/><p className="figure-analysis"><b>图解分析：</b>{fig.caption}</p></figure>}{p.sections.map(s=><div key={s.title}><h3>{s.title}</h3>{s.text.split('\n\n').map((part,j)=><p key={j}>{part}</p>)}</div>)}<div className="reading-guide"><span>{p.readingGuide.priority}</span><h3>本篇专属阅读路径</h3><p><b>先读：</b>{p.readingGuide.first}</p><p><b>重点：</b>{p.readingGuide.focus}</p><p><b>下一步：</b>{p.readingGuide.next}</p></div></section>})}
 <section className="comparison" id="compare"><p className="eyebrow">TODAY AT A GLANCE</p><h2>材料、方法与证据状态</h2><div className="table-wrap"><table><thead><tr><th>材料</th><th>方法</th><th>核心物性/问题</th><th>全文状态</th><th>推荐</th></tr></thead><tbody>{report.papers.map(p=><tr key={p.title}><td>{p.material}</td><td>{p.method}</td><td>{p.conclusion.slice(0,72)}…</td><td>{p.access.includes('全文精读')?'全文精读':'摘要级'}</td><td>{p.rating}</td></tr>)}</tbody></table></div><h3>板块统计</h3><p>{Object.entries(counts).map(([k,v])=>`${k} ${v}篇`).join('；')}。正式期刊{formal}篇，arXiv独立稿{report.papers.length-formal}篇；全文精读{full}篇，摘要级{report.papers.length-full}篇。</p></section>
 <section className="search-note" id="search-log"><p className="eyebrow">SEARCH LOG</p><h2>逐轨检索、访问与去重记录</h2><p><b>实际时间窗：</b>{report.searchWindow}</p>{report.searchTerms.map(x=><p key={x}>{x}</p>)}</section></article></div></main>;
}
