/* eslint-disable @next/next/no-html-link-for-pages, @next/next/no-img-element */
import type {Metadata} from 'next';
import report from '../../../content/reports/2026-09-30.json';

export const metadata:Metadata={title:'2026-09-30 简报｜每日文献简报',description:report.headline};
const figures:Record<string,{src:string;title:string;caption:string}>={
 'Far-field terahertz spectroscopy across the charge-density-wave transition in 2H-NbSe$_2$':{src:'/reports/2026-09-30/nbse2-cvt.svg',title:'2H-NbSe₂：I₂-CVT 温区与 THz 测量窗口',caption:'根据 arXiv:2609.36125 Methods 的 I₂=3 mg/cm³、源区 850 °C、生长区 700 °C、7 天及 12–52 K 测量窗口原创重绘。1.5 THz 特征与亚 THz 振荡跨 33 K CDW 转变减弱；这支持 CDW 相关，却不能单独证明低频一定是缺陷钉扎相位模。非论文原图。'},
 'Magnetic properties and Fermi-surface topology of kagome magnet HoV$_6$Sn$_6$':{src:'/reports/2026-09-30/hov6sn6-flux.svg',title:'HoV₆Sn₆：Sn Flux 放行窗口与高场振荡',caption:'根据 arXiv:2609.36258 生长段、Fig.3–4 重绘。1:6:20 配比，1125 °C/12 h 后 2 °C/h 降至 780 °C 倾析；约 54/150 T 与 8.95 kT 分支性质不同，约 600 T 仍未被计算复现。非论文原图。'},
 'Evolution of Magnetism in Ce$_4$Ge$_7$ under Magnetic Field and Pressure':{src:'/reports/2026-09-30/ce4ge7-evidence.svg',title:'Ce₄Ge₇：生长、场与压力量标',caption:'依据 arXiv:2609.37129 Methods、Fig.1–4 原创重绘。In Flux 1:1:40、1150 °C/20 h 冷至 500 °C；7.3 K 磁序、2 K 下 1.3 T 变磁和约 10.2 GPa 临界压力分别来自不同测量维度，不应连成未经测得的连续相界。非论文原图。'}
};
export default function Report(){
 const full=report.papers.filter(p=>p.access.includes('全文精读')).length;
 const formal=report.papers.filter(p=>p.tags.includes('正式期刊')).length;
 const counts=report.papers.reduce<Record<string,number>>((m,p)=>(m[p.category]=(m[p.category]||0)+1,m),{});
 return <main className="report-page"><header className="site-header"><a className="brand" href="/"><span className="brand-mark">文</span><span>每日文献简报</span></a><nav aria-label="主导航"><a className="active" href="/reports/2026-09-30">今日简报</a><a href="/materials">材料时间线</a><a href="/search">智能检索</a><a href="/weekly">本周趋势</a><a href="/workspace">我的研究</a><a href="/archive">归档</a></nav><div className="live-chip"><span/> 每日更新</div></header>
 <div className="report-hero"><div><p className="eyebrow">DAILY REPORT · ISSUE 036</p><h1>每日文献简报</h1><p>2026 年 9 月 30 日 · 北京时间</p></div><div className="report-summary"><b>今日判断</b><p>{report.headline}</p><div><span>{report.papers.length} 篇入选</span><span>{full} 篇全文精读</span><span>正式期刊 {formal} 篇</span></div></div></div>
 <div className="report-layout"><aside className="report-toc"><p>本期目录</p>{report.papers.map((p,i)=><a key={p.title} href={'#paper-'+(i+1)}>{String(i+1).padStart(2,'0')} · {p.material.slice(0,16)}</a>)}<a href="#compare">汇总统计</a><a href="#search-log">检索日志</a></aside><article className="report-content">
 <section className="report-lede"><p className="eyebrow">TODAY&apos;S SIGNAL</p><h2>今日要点与访问边界</h2><p>{report.hotspot}</p><ol><li><b>官方新稿：</b>arXiv cond-mat/new 9 月 30 日列出 119 篇 New submissions，逐条筛过题名，并核查候选摘要；纳入 {report.papers.length} 篇。</li><li><b>正式期刊：</b>已逐刊核对；截至本轮无经确认的当天高相关新稿。ACS、Science、Wiley 等受限轨道有待补扫，不能声称全天零稿。</li><li><b>阅读分级：</b>实际读取公开正文、Methods 与关键图注的 {full} 篇标为全文精读；可访问未读和仅摘要条目各列边界。</li><li><b>机构访问：</b>未建立已认证浙江大学机构会话，未取订阅 PDF；图解为依据公开数值原创重绘。</li></ol></section>
 {report.papers.map((p,i)=>{const fig=figures[p.title];return <section className="paper-detail" id={'paper-'+(i+1)} key={p.title}><div className="paper-kicker"><span>{String(i+1).padStart(2,'0')} · {p.category}</span><b>{p.access.includes('全文精读')?'全文精读':'摘要级'} · 推荐 {p.rating}</b></div><h2>{p.material}｜{p.title}</h2><div className="tag-row">{p.tags.map(t=><span key={t}>{t}</span>)}</div><div className="meta-grid"><div className="meta-item"><span>来源</span><b>{p.journal}</b></div><div className="meta-item"><span>日期</span><b>{p.date}</b></div><div className="meta-item"><span>生长 / 方法</span><b>{p.method}</b></div><div className="meta-item"><span>作者</span><b>{p.authors}</b></div><div className="meta-item institution-item"><span>主要单位</span><b>{p.institutions}</b></div></div><p className="links"><a href={p.doi}>DOI / arXiv ↗</a>{p.fullText&&p.fullText!==p.doi&&<a href={p.fullText}> 公开全文 ↗</a>}</p><p className="version-note"><b>版本与阅读范围：</b>{p.versionNote} {p.access}</p><div className="paper-conclusion"><span>CONCLUSION</span><h3>这篇论文讲了什么故事</h3><p>{p.conclusion}</p></div>{fig&&<figure className="data-figure"><figcaption><b>{fig.title}</b><span>根据公开正文数值重绘，并非论文原图</span></figcaption><img className="report-figure-image" src={fig.src} alt={fig.title}/><p className="figure-analysis"><b>图解分析：</b>{fig.caption}</p></figure>}{p.sections.map(s=><div key={s.title}><h3>{s.title}</h3>{s.text.split('\n\n').map((part,j)=><p key={j}>{part}</p>)}</div>)}<div className="reading-guide"><span>{p.readingGuide.priority}</span><h3>本篇专属阅读路径</h3><p><b>先读：</b>{p.readingGuide.first}</p><p><b>重点：</b>{p.readingGuide.focus}</p><p><b>下一步：</b>{p.readingGuide.next}</p></div></section>})}
 <section className="comparison" id="compare"><p className="eyebrow">TODAY AT A GLANCE</p><h2>材料、方法与证据状态</h2><div className="table-wrap"><table><thead><tr><th>材料</th><th>方法</th><th>核心物性/问题</th><th>全文状态</th><th>推荐</th></tr></thead><tbody>{report.papers.map(p=><tr key={p.title}><td>{p.material}</td><td>{p.method}</td><td>{p.conclusion.slice(0,72)}…</td><td>{p.access.includes('全文精读')?'全文精读':'摘要级'}</td><td>{p.rating}</td></tr>)}</tbody></table></div><h3>板块统计</h3><p>{Object.entries(counts).map(([k,v])=>`${k} ${v}篇`).join('；')}。正式期刊{formal}篇，arXiv独立稿{report.papers.length-formal}篇；全文精读{full}篇，摘要级{report.papers.length-full}篇。</p></section>
 <section className="search-note" id="search-log"><p className="eyebrow">SEARCH LOG</p><h2>逐轨检索、访问与去重记录</h2><p><b>实际时间窗：</b>{report.searchWindow}</p>{report.searchTerms.map(x=><p key={x}>{x}</p>)}</section></article></div></main>;
}


