/* eslint-disable @next/next/no-html-link-for-pages, @next/next/no-img-element */
import type { Metadata } from 'next';
import report from '../../../content/reports/2026-09-13.json';

export const metadata: Metadata={title:'2026-09-13 简报｜每日文献简报',description:report.headline};
const ids=report.papers.map((_,i)=>`paper-${i+1}`);

function EvidenceFigures(){return <section id="figures">
 <figure className="data-figure"><figcaption><b>原创图解 1｜α-RuCl₃：应变—光谱—交换相互作用</b><span>根据npj Quantum Materials开放全文图2–4与Methods数值原创重绘，并非论文原图</span></figcaption><img className="report-figure-image" src="/reports/2026-09-13/rucl3-strain-evidence.svg" alt="RuCl3应变调控Kitaev交换证据链"/><p className="figure-analysis"><b>图解分析：</b>先用3.2–350 nm厚度序列排除薄膜干涉伪峰位，再看拉伸使1.2 eV三重态增强、带隙降低；计算只支持K/J定性上升。PDMS实际应变和晶向未标定，因此不能把横轴读成精确交换常数。</p></figure>
 <figure className="data-figure dark-data"><figcaption><b>原创图解 2｜SrCu₂(BO₃)₂：结构与磁性的高压分层</b><span>根据PRB对应arXiv:2609.06472图1–4重绘，并非论文原图</span></figcaption><img className="report-figure-image" src="/reports/2026-09-13/srcubo-pressure-map.svg" alt="SrCu2BO3高压结构与磁性相图"/><p className="figure-analysis"><b>图解分析：</b>4–5 GPa的卫星峰/νQ改变界定两个单斜结构区，而中心峰与1/T₁把短程AFL和无隙3D AFM分开。T<sub>N</sub>在4→5.5 GPa从约3 K跃至10.5 K，是结构重排增强层间耦合的关键线索，但空间群仍需同步衍射确认。</p></figure>
 <p className="version-note"><b>图片来源与许可：</b>两张SVG均依据合法公开全文中的方法与定量数据原创重绘，没有复制论文图形表达；它们用于说明证据层级，不能替代原始曲线。</p>
 </section>}

export default function Report(){const full=report.papers.filter(p=>p.access.includes('全文精读')).length;return <main className="report-page"><header className="site-header"><a className="brand" href="/"><span className="brand-mark">文</span><span>每日文献简报</span></a><nav><a className="active" href="/reports/2026-09-13">今日简报</a><a href="/#topics">研究板块</a><a href="/archive">往期归档</a><a href="/search">智能检索</a></nav><div className="live-chip"><span/> 每日 08:00 更新</div></header>
 <div className="report-hero"><div><p className="eyebrow">DAILY REPORT · ISSUE 019</p><h1>每日文献简报</h1><p>2026 年 9 月 13 日 · 北京时间</p></div><div className="report-summary"><b>今日判断</b><p>{report.headline}</p><div><span>{report.papers.length} 篇入选</span><span>{full} 篇全文精读</span><span>4 个主板块</span></div></div></div>
 <div className="report-layout"><aside className="report-toc"><p>本期目录</p>{report.papers.map((p,i)=><a key={p.title} href={`#${ids[i]}`}>{String(i+1).padStart(2,'0')} · {p.material}</a>)}<a href="#figures">原创图解</a><a href="#compare">横向对比</a><a href="#search-log">检索日志</a></aside><article className="report-content">
  <section className="report-lede"><p className="eyebrow">TODAY&apos;S SIGNAL</p><h2>今日要点与阅读边界</h2><p>{report.hotspot}</p><ol><li><b>按三日窗口回溯。</b>9月13日为周日，当天无新公告；实际窗口为9月11—13日。</li><li><b>正式期刊优先。</b>12篇均为正式期刊上线/accepted论文，4篇取得合法公开全文。</li><li><b>arXiv只作全文来源。</b>两篇公开稿对应本期PRB/PRL正式条目，不重复计数。</li><li><b>访问边界。</b>无可复用的aTrust/CARSI登录会话；8篇按摘要/元数据整理，未知参数未补写。</li></ol></section>
  <EvidenceFigures/>
  {report.papers.map((p,i)=><section className="paper-detail" id={ids[i]} key={p.title}><div className="paper-kicker"><span>{String(i+1).padStart(2,'0')} · {p.category}</span><b>{p.access.includes('全文精读')?'全文精读':'摘要/元数据'} · 推荐 {p.rating}</b></div><h2>{p.material}｜{p.title}</h2><div className="tag-row">{p.tags.map(t=><span key={t}>{t}</span>)}</div><div className="meta-grid"><div className="meta-item"><span>来源</span><b>{p.journal}</b></div><div className="meta-item"><span>日期</span><b>{p.date}</b></div><div className="meta-item"><span>生长 / 方法</span><b>{p.method}</b></div><div className="meta-item"><span>作者</span><b>{p.authors}</b></div><div className="meta-item institution-item"><span>主要单位</span><b>{p.institutions}</b></div></div><p className="links"><a href={p.doi}>DOI / 出版社 ↗</a>{p.fullText&&<a href={p.fullText}>全文来源 ↗</a>}</p><p className="version-note"><b>版本与阅读范围：</b>{p.versionNote} {p.access}</p><div className="paper-conclusion"><span>CONCLUSION</span><h3>这篇论文讲了什么故事</h3><p>{p.conclusion}</p></div>{p.sections.map(s=><div key={s.title}><h3>{s.title}</h3><p>{s.text}</p></div>)}<div className="reading-guide"><span>{p.readingGuide.priority}</span><h3>本篇专属阅读路径</h3><p><b>先读：</b>{p.readingGuide.first}</p><p><b>重点：</b>{p.readingGuide.focus}</p><p><b>下一步：</b>{p.readingGuide.next}</p></div></section>)}
  <section className="comparison" id="compare"><p className="eyebrow">COMPARISON</p><h2>本期横向对比</h2><div className="table-wrap"><table><thead><tr><th>板块</th><th>材料</th><th>生长 / 方法</th><th>故事结论</th><th>推荐</th></tr></thead><tbody>{report.papers.map(p=><tr key={p.title}><td>{p.category}</td><td>{p.material}</td><td>{p.method}</td><td>{p.conclusion.slice(0,72)}…</td><td>{p.rating}</td></tr>)}</tbody></table></div></section>
  <section className="search-note" id="search-log"><p className="eyebrow">SEARCH LOG</p><h2>检索、访问与去重记录</h2><p><b>时间窗：</b>{report.searchWindow}</p>{report.searchTerms.map(x=><p key={x}>{x}</p>)}<p><b>全文状态：</b>α-RuCl₃、SrCu₂(BO₃)₂、LaCoO₃及倾斜层错论文完成全文精读；其余8篇为摘要/元数据级。机构订阅正文未公开上传，也未用经验补写。</p></section>
 </article></div></main>}
