/* eslint-disable @next/next/no-html-link-for-pages */
import type {Metadata} from 'next';
import report from '../../../content/reports/2026-09-15.json';

export const metadata:Metadata={title:'2026-09-15 简报｜每日文献简报',description:report.headline};

export default function Report(){const full=report.papers.filter(p=>p.access.includes('全文精读')).length;return <main className="report-page">
<header className="site-header"><a className="brand" href="/"><span className="brand-mark">文</span><span>每日文献简报</span></a><nav aria-label="主导航"><a className="active" href="/reports/2026-09-15">今日简报</a><a href="/materials">材料时间线</a><a href="/search">智能检索</a><a href="/weekly">本周趋势</a><a href="/workspace">我的研究</a><a href="/archive">归档</a></nav><div className="live-chip"><span/> 每日 08:00 更新</div></header>
<div className="report-hero"><div><p className="eyebrow">DAILY REPORT · ISSUE 021</p><h1>每日文献简报</h1><p>2026 年 9 月 15 日 · 北京时间</p></div><div className="report-summary"><b>今日判断</b><p>{report.headline}</p><div><span>{report.papers.length} 篇入选</span><span>{full} 篇全文精读</span><span>正式期刊 1 篇</span></div></div></div>
<div className="report-layout"><aside className="report-toc"><p>本期目录</p><a href="#paper-1">01 · 混合阳离子钙钛矿</a><a href="#compare">今日概览</a><a href="#search-log">检索日志</a></aside><article className="report-content">
<section className="report-lede"><p className="eyebrow">TODAY&apos;S SIGNAL</p><h2>今日要点与阅读边界</h2><p>{report.hotspot}</p><ol><li><b>严格使用当天窗口。</b>今天已有1篇高相关正式论文，因此没有用前两日论文凑数。</li><li><b>正式期刊优先。</b>按APS、Nature、AAAS、Wiley、ACS、CG&amp;D和JCG逐轨核对后，ACS单晶异质结是唯一纳入项。</li><li><b>全文等级为零。</b>ACS页面与PDF均返回403，当前无可复用机构订阅会话；所有未知实验项都明确登记。</li><li><b>arXiv未重复推送。</b>检索时cond-mat/new仍是9月14日公告，与昨日清单去重后没有独立新增。</li></ol></section>
<section className="overview"><p className="eyebrow">FIGURE STATUS</p><h2>今日不嵌入论文图</h2><p>本期没有获得可合法读取的正文、Methods或补充材料，也没有足够公开数值用于定量重绘。为了避免用通用示意图制造“已精读”的错觉，今天只保留证据边界和全文获取后的检查清单。</p></section>
{report.papers.map((p,i)=><section className="paper-detail" id={'paper-'+(i+1)} key={p.title}><div className="paper-kicker"><span>{String(i+1).padStart(2,'0')} · {p.category}</span><b>元数据级 · 推荐 {p.rating}</b></div><h2>{p.material}｜{p.title}</h2><div className="tag-row">{p.tags.map(t=><span key={t}>{t}</span>)}</div><div className="meta-grid"><div className="meta-item"><span>来源</span><b>{p.journal}</b></div><div className="meta-item"><span>上线日期</span><b>{p.date}</b></div><div className="meta-item"><span>生长 / 方法</span><b>{p.method}</b></div><div className="meta-item"><span>作者</span><b>{p.authors}</b></div><div className="meta-item institution-item"><span>主要单位</span><b>{p.institutions}</b></div></div><p className="links"><a href={p.doi}>DOI / 出版社 ↗</a></p><p className="version-note"><b>版本与阅读范围：</b>{p.versionNote} {p.access}</p><div className="paper-conclusion"><span>CONCLUSION</span><h3>这篇论文讲了什么故事</h3><p>{p.conclusion}</p></div>{p.sections.map(s=><div key={s.title}><h3>{s.title}</h3>{s.text.split('\n\n').map((part,j)=><p key={j}>{part}</p>)}</div>)}<div className="reading-guide"><span>{p.readingGuide.priority}</span><h3>本篇专属阅读路径</h3><p><b>先读：</b>{p.readingGuide.first}</p><p><b>重点：</b>{p.readingGuide.focus}</p><p><b>下一步：</b>{p.readingGuide.next}</p></div></section>)}
<section className="comparison" id="compare"><p className="eyebrow">TODAY AT A GLANCE</p><h2>本期汇总</h2><div className="table-wrap"><table><thead><tr><th>材料</th><th>生长方法</th><th>主要物性</th><th>全文状态</th><th>推荐</th></tr></thead><tbody><tr><td>混合阳离子钙钛矿单晶异质结</td><td>正文未取得</td><td>X射线探测，数据未取得</td><td>仅元数据</td><td>B+</td></tr></tbody></table></div></section>
<section className="search-note" id="search-log"><p className="eyebrow">SEARCH LOG</p><h2>逐轨检索、访问与去重记录</h2><p><b>时间窗：</b>{report.searchWindow}</p>{report.searchTerms.map(x=><p key={x}>{x}</p>)}</section>
</article></div></main>}
