/* eslint-disable @next/next/no-html-link-for-pages */
import report from '../content/reports/2026-09-02.json';
const ids=report.papers.map((_,i)=>`paper-${i+1}`);
const accents=['amber','blue','green'];
export default function Home(){return <main><header className="site-header"><a className="brand" href="#top"><span className="brand-mark">晶</span><span>晶体生长和物性调控</span></a><nav><a className="active" href="/reports/2026-09-02">今日简报</a><a href="/archive">往期归档</a><a href="/search">文献检索</a></nav><div className="live-chip"><span/> 每日 08:00 更新</div></header>
<section className="hero" id="top"><div className="hero-copy"><p className="eyebrow">CRYSTAL GROWTH · PHYSICAL PROPERTIES</p><h1>从生长窗口到<br/><em>物性证据链</em></h1><p className="hero-lead">固定核查 APS/PR、Nature、Science、Advanced Materials/AFM、Nano Letters、ACS Nano、JACS、Chemistry of Materials、npj Quantum Materials，并补充 arXiv、高温超导与重费米子研究。</p><div className="hero-actions"><a className="primary-btn" href="/reports/2026-09-02">阅读今日简报 <span>↘</span></a><a className="secondary-btn" href="/search">检索与提问</a><span className="date-stamp">2026.09.02 · 第 008 期</span></div></div><div className="crystal-field"><div className="orb orb-a"/><div className="orb orb-b"/><div className="orb orb-c"/><div className="beam beam-a"/><div className="beam beam-b"/><div className="beam beam-c"/><div className="field-label"><b>13 PAPERS</b><span>growth · structure · properties</span></div><p>今日焦点 · Kondo 向列序与镍酸盐边界</p></div></section>
<section className="ticker"><div><strong>13</strong><span>入选论文</span></div><div><strong>05</strong><span>全文精读</span></div><div><strong>08</strong><span>正式期刊</span></div><div><strong>05</strong><span>arXiv 新稿</span></div><p>检索窗口：北京时间 2026.09.02 当天 · 已按 DOI / arXiv ID / 题目去重</p></section>
<section className="latest"><div className="section-heading"><div><p className="eyebrow">DAILY BRIEFING</p><h2>今日要点</h2></div><span className="status-pill">不设篇数上限 · 相关即收录</span></div><div className="insight-grid"><article className="lead-insight"><span className="number">01</span><div><p className="kicker">首要判断</p><h3>结构几何不是镍酸盐超导的充分条件</h3><p>{report.hotspot}</p></div></article><article className="short-insight"><span>02</span><h3>重费米子实空间成像</h3><p>USbTe 将 Kondo 杂化、C4→C2 破缺和自旋选择信号放进同一 STM 证据链。</p></article><article className="short-insight"><span>03</span><h3>可执行生长窗口</h3><p>HPHT Flux 和 GaAs/GaAsP MOCVD 全文给出压力、温度、层厚与掺杂等实验坐标。</p></article></div></section>
<section className="papers"><div className="section-heading"><div><p className="eyebrow">ALL RELATED PAPERS</p><h2>本期全部相关论文</h2></div><a href="/reports/2026-09-02#compare">查看方法对比 →</a></div><div className="paper-list">{report.papers.map((p,i)=><a className={`paper-row ${accents[i%accents.length]}`} href={`/reports/2026-09-02#${ids[i]}`} key={p.title}><span className="row-index">{String(i+1).padStart(2,'0')}</span><div className="paper-main"><div className="paper-meta"><span>{p.method}</span><span>{p.journal}</span></div><h3>{p.title}</h3><p>{p.sections[0].text.slice(0,115)}…</p></div><div className="paper-material"><strong>{p.material}</strong><span>推荐 {p.rating}</span></div><span className="arrow">→</span></a>)}</div></section>
<footer><div className="brand"><span className="brand-mark">晶</span><span>晶体生长和物性调控</span></div><p>每日晶体生长与物性文献简报</p><p>资料仅用于科研交流 · 原文版权归作者与出版社所有</p></footer></main>}
