/* eslint-disable @next/next/no-html-link-for-pages */
import report from '../content/reports/2026-09-16.json';
import HomePersonalDigest from './research/HomePersonalDigest';
const categories=[
 {name:'晶体生长和物性调控',note:'Flux、CVT、MBE、外延、缺陷与工艺窗口',mark:'晶',featured:true},
 {name:'高温与非常规超导',note:'铁基配对、非线性电声耦合与候选材料',mark:'超'},
 {name:'重费米子与量子临界',note:'Kondo尺度、无序破对与隐藏有序',mark:'重'},
 {name:'磁性、拓扑与自旋',note:'Floquet拓扑、交错磁体、环交换与magnon',mark:'磁'},
 {name:'二维材料与量子器件',note:'二维接触、铁电输运与graphene磁读出',mark:'器'}];
export default function Home(){const full=report.papers.filter(p=>p.access.includes('全文精读')||p.access.includes('补充材料精读')).length;return <main>
 <header className="site-header"><a className="brand" href="/"><span className="brand-mark">文</span><span>每日文献简报</span></a><nav aria-label="主导航"><a className="active" href="/reports/2026-09-16">今日简报</a><a href="/materials">材料时间线</a><a href="/search">智能检索</a><a href="/weekly">本周趋势</a><a href="/workspace">我的研究</a><a href="/archive">归档</a></nav><div className="live-chip"><span/> 每日 08:00 更新</div></header>
 <section className="hero" id="top"><div className="hero-copy"><p className="eyebrow">DAILY LITERATURE BRIEF · EVIDENCE FIRST</p><h1>每天把复杂论文，<br/><em>整理成可核查的证据。</em></h1><p className="hero-lead">从正式期刊、作者公开稿和 arXiv 全文中，拆解问题、样品、生长、测量、关键证据、局限和下一步实验。访问不到的数据会明确标记，不用经验补写。</p><form className="home-quick-search" action="/search"><input aria-label="首页文献关键词" name="query" placeholder="输入材料、作者或生长方法"/><button>检索文献 →</button></form><div className="hero-actions"><a className="primary-btn" href="/reports/2026-09-16">阅读今日简报 <span>→</span></a><a className="secondary-btn" href="/search">智能检索与证据问答</a><span className="date-stamp">2026.09.16 · 第 022 期</span></div></div><div className="crystal-field"><div className="orb orb-a"/><div className="orb orb-b"/><div className="orb orb-c"/><div className="beam beam-a"/><div className="beam beam-b"/><div className="beam beam-c"/><div className="field-label"><b>{String(report.papers.length).padStart(2,'0')} PAPERS</b><span>{full} full/SI reads · 5 active sections</span></div><p>正式期刊优先 · 全文证据分级 · 原创图解</p></div></section>
 <section className="ticker"><div><strong>{report.papers.length}</strong><span>入选论文</span></div><div><strong>{full}</strong><span>全文/SI 精读</span></div><div><strong>03</strong><span>正式期刊</span></div><div><strong>05</strong><span>研究板块</span></div><p>已核对 DOI、版本关系、全文可访问状态和历史去重</p></section>
 <HomePersonalDigest/>
 <section className="research-entry-grid"><a href="/materials"><span>01 · MATERIAL STORYLINES</span><h2>跨期材料时间线</h2><p>追踪同一材料从生长、缺陷、基础物性到压力、应变、掺杂和争议。</p><b>查看材料档案 →</b></a><a href="/workspace"><span>02 · PERSONAL RESEARCH DESK</span><h2>我的研究工作台</h2><p>设置关注方向、整理论文项目，并记录每一炉晶体与每一次物性测量。</p><b>进入工作台 →</b></a><a href="/weekly"><span>03 · WEEKLY EVIDENCE</span><h2>本周趋势仪表盘</h2><p>根据站内真实记录统计热点材料、生长方法、测量技术和来源比例。</p><b>查看本周趋势 →</b></a></section>
 <section className="topic-hub" id="topics"><div className="section-heading"><div><p className="eyebrow">RESEARCH SECTIONS</p><h2>按研究方向阅读</h2></div><span className="status-pill">一篇只归一个主板块 · 标签支持交叉检索</span></div><div className="topic-grid">{categories.map(c=>{const papers=report.papers.filter(p=>p.category===c.name);return <article className={c.featured?'topic-card featured':'topic-card'} key={c.name}><div className="topic-mark">{c.mark}</div><div><span>{papers.length} 篇</span><h3>{c.name}</h3><p>{c.note}</p><details><summary>展开板块论文（{papers.length}）</summary>{papers.map(p=><a href={`/reports/2026-09-16#paper-${report.papers.indexOf(p)+1}`} key={p.title}>{p.material} <b>→</b></a>)}{!papers.length&&<p>本期暂无新增，可在检索页查看历史文献。</p>}<a href={'/search?category='+encodeURIComponent(c.name)}>检索整个板块 →</a></details></div></article>})}</div></section>
 <section className="latest"><div className="section-heading"><div><p className="eyebrow">TODAY&apos;S SIGNAL</p><h2>今日判断</h2></div><a href="/reports/2026-09-16">查看完整证据链 →</a></div><div className="insight-grid"><article className="lead-insight"><span className="number">01</span><div><p className="kicker">STRUCTURE AND DEFECTS</p><h3>结构与缺陷必须进入证据链</h3><p>{report.hotspot}</p></div></article><article className="short-insight"><span>02</span><h3>正式期刊与预印本并行</h3><p>正式期刊3篇、arXiv全文10篇；ACS受限条目只采用可核查摘要，不用arXiv替代正式检索。</p></article><article className="short-insight"><span>03</span><h3>隐藏变量成为主角</h3><p>从接触边缘缺陷、Floquet Berry曲率到无序破对和亚Néel动力学，今天的论文都在把隐变量转成可检验坐标。</p></article></div></section>
 <section className="papers home-interactive"><div className="section-heading"><div><p className="eyebrow">LATEST PAPERS</p><h2>本期全部论文</h2></div><a href="/search">筛选全站文献 →</a></div><div className="paper-list">{report.papers.map((p,i)=><details className="home-paper-card" key={p.title}><summary><span className="home-card-number">{String(i+1).padStart(2,'0')}</span><span><span className="home-card-meta">{p.category} · {p.material}</span><span className="home-card-title">{p.title}</span><span className="home-card-authors">{p.authors.split(';').slice(0,3).join(' · ')}{p.authors.split(';').length>3?' 等':''}<small>{p.institutions}</small></span></span><span className="home-card-toggle" aria-hidden="true">+</span></summary><div className="home-card-content"><h3>Conclusion｜这篇论文讲了什么故事</h3><p>{p.conclusion}</p><h3>本篇阅读路径</h3><p>{p.readingGuide.first}</p><p><b>关注：</b>{p.readingGuide.focus}</p><a href={`/reports/2026-09-16#paper-${i+1}`}>阅读完整证据链 →</a></div></details>)}</div></section>
 <footer><div className="brand"><span className="brand-mark">晶</span><span>每日文献简报</span></div><p>晶体生长和物性调控 · 超导 · 重费米子 · 磁性拓扑 · 二维材料</p><p>内容仅供科研交流 · 原文版权属于作者和出版社</p></footer></main>}



