/* eslint-disable @next/next/no-html-link-for-pages */
import report from '../content/reports/2026-09-01.json';
const ids=['zrnx','tin','nno-nmo','algaas','ptsige','yig','gesn'];
const accents=['amber','blue','green','amber','blue','green','amber'];
export default function Home(){return <main><header className="site-header"><a className="brand" href="#top"><span className="brand-mark">晶</span><span>晶体生长和物性调控</span></a><nav><a className="active" href="/reports/2026-09-01">今日简报</a><a href="/archive">往期归档</a><a href="/search">文献检索</a></nav><div className="live-chip"><span/> 每日 08:00 更新</div></header>
<section className="hero" id="top"><div className="hero-copy"><p className="eyebrow">CRYSTAL GROWTH · PHYSICAL PROPERTIES</p><h1>从生长窗口到<br/><em>物性证据链</em></h1><p className="hero-lead">聚焦 Flux、CVT、全部 Physical Review 系列、Nature 系列、Advanced Materials、Nano Letters、arXiv，并新增高温超导与重费米子专题。</p><div className="hero-actions"><a className="primary-btn" href="/reports/2026-09-01">阅读今日简报 <span>↘</span></a><a className="secondary-btn" href="/search">检索与提问</a><span className="date-stamp">2026.09.01 · 第 007 期</span></div></div><div className="crystal-field"><div className="orb orb-a"/><div className="orb orb-b"/><div className="orb orb-c"/><div className="beam beam-a"/><div className="beam beam-b"/><div className="beam beam-c"/><div className="field-label"><b>07 PAPERS</b><span>growth · defects · properties</span></div><p>今日焦点 · 超导膜与局域结构调控</p></div></section>
<section className="ticker"><div><strong>07</strong><span>入选论文</span></div><div><strong>07</strong><span>全文详读</span></div><div><strong>06</strong><span>实验研究</span></div><div><strong>02</strong><span>重要修订</span></div><p>检索窗口：北京时间 2026.08.30–09.01 · 已按 DOI / arXiv ID / 题目去重</p></section>
<section className="latest"><div className="section-heading"><div><p className="eyebrow">DAILY BRIEFING</p><h2>今日要点</h2></div><span className="status-pill">不设篇数上限 · 相关即收录</span></div><div className="insight-grid"><article className="lead-insight"><span className="number">01</span><div><p className="kicker">首要判断</p><h3>晶体质量必须进入真实物性与器件闭环</h3><p>{report.hotspot}</p></div></article><article className="short-insight"><span>02</span><h3>超导与缺陷</h3><p>ZrNₓ 的 Griffiths 临界、TiN 的马赛克度与 PtSiGe 的微波损耗形成三层对照。</p></article><article className="short-insight"><span>03</span><h3>局域结构调控</h3><p>轨道反转、晶相插层与 Sn–Sn 近邻表明宏观成分不再是唯一材料坐标。</p></article></div></section>
<section className="papers"><div className="section-heading"><div><p className="eyebrow">ALL RELATED PAPERS</p><h2>本期全部相关论文</h2></div><a href="/reports/2026-09-01#compare">查看方法对比 →</a></div><div className="paper-list">{report.papers.map((p,i)=><a className={`paper-row ${accents[i]}`} href={`/reports/2026-09-01#${ids[i]}`} key={p.title}><span className="row-index">{String(i+1).padStart(2,'0')}</span><div className="paper-main"><div className="paper-meta"><span>{p.method}</span><span>{p.journal}</span></div><h3>{p.title}</h3><p>{p.sections[0].text.slice(0,115)}…</p></div><div className="paper-material"><strong>{p.material}</strong><span>推荐 {p.rating}</span></div><span className="arrow">→</span></a>)}</div></section>
<footer><div className="brand"><span className="brand-mark">晶</span><span>晶体生长和物性调控</span></div><p>每日晶体生长与物性文献简报</p><p>资料仅用于科研交流 · 原文版权归作者与出版社所有</p></footer></main>}
