/* eslint-disable @next/next/no-html-link-for-pages, @next/next/no-img-element */
import type {Metadata} from 'next';
import report from '../../../content/reports/2026-09-27.json';

export const metadata:Metadata={title:'2026-09-27 简报｜每日文献简报',description:report.headline};
const figures:Record<string,{src:string;title:string;caption:string}>={
 "Atmosphere-Controlled Valence Engineering of Eu in Aluminate Crystals Enabling High-Performance Temperature Sensing and Flexible X-Ray Imaging":{src:"/reports/2026-09-27/eu-valence-performance.svg",title:"Eu价态工程的两条功能路径与已公开指标",caption:"左侧是完全还原Eu2+路线：辐射发光循环后保持117.5%、光产额55917±573 photons MeV−1、柔性成像分辨率11.7 lp mm−1（20% MTF）。右侧是Eu2+/Eu3+共存路线：550–625 K内FIR绝对/相对灵敏度0.226 K−1和0.97% K−1，FWHM灵敏度0.238 nm K−1。图只整理摘要已公开数字，不能替代价态定量或完整标定曲线。"},
 "Percolation-Driven β-Relaxation Enables Resonant Acceleration of Crystallization in Amorphous Phase-Change Materials":{src:"/reports/2026-09-27/gst-relaxation.svg",title:"β弛豫—渗流—结晶加速的证据链示意",caption:"作者的机制链是：可动原子网络接近渗流→β弛豫提供协同运动通道→扩散/无扩散结晶路径切换；当超声频率接近β弛豫频率时，加速最大。该图是根据摘要重绘的因果结构，不包含正文尚未公开的频率、功率或时间常数，因此不能证明共振峰本身。"}
};
export default function Report(){
 const full=report.papers.filter(p=>p.access.includes('全文精读')).length;
 const formal=report.papers.filter(p=>p.tags.includes('正式期刊')).length;
 const counts=report.papers.reduce<Record<string,number>>((m,p)=>(m[p.category]=(m[p.category]||0)+1,m),{});
 return <main className="report-page"><header className="site-header"><a className="brand" href="/"><span className="brand-mark">文</span><span>每日文献简报</span></a><nav aria-label="主导航"><a className="active" href="/reports/2026-09-27">今日简报</a><a href="/materials">材料时间线</a><a href="/search">智能检索</a><a href="/weekly">本周趋势</a><a href="/workspace">我的研究</a><a href="/archive">归档</a></nav><div className="live-chip"><span/> 每日更新</div></header>
 <div className="report-hero"><div><p className="eyebrow">DAILY REPORT · ISSUE 033</p><h1>每日文献简报</h1><p>2026 年 9 月 27 日 · 北京时间</p></div><div className="report-summary"><b>今日判断</b><p>{report.headline}</p><div><span>{report.papers.length} 篇入选</span><span>{full} 篇全文精读</span><span>正式期刊 {formal} 篇</span></div></div></div>
 <div className="report-layout"><aside className="report-toc"><p>本期目录</p>{report.papers.map((p,i)=><a key={p.title} href={'#paper-'+(i+1)}>{String(i+1).padStart(2,'0')} · {p.material.slice(0,16)}</a>)}<a href="#compare">汇总统计</a><a href="#search-log">检索日志</a></aside><article className="report-content">
 <section className="report-lede"><p className="eyebrow">TODAY&apos;S SIGNAL</p><h2>今日要点与访问边界</h2><p>{report.hotspot}</p><ol><li><b>当天优先：</b>纳入3篇9月27日Advanced Materials新论文，另回补2篇9月26日高相关正式论文。</li><li><b>正式期刊优先：</b>本期5篇全部来自出版社条目；周日arXiv无独立new批次，不重复Friday批次。</li><li><b>访问边界：</b>已读摘要与元数据，正文、Methods和SI尚未取得，因此生长与测量缺项逐项标明。</li><li><b>证据审慎：</b>把摘要中的直接观察、作者机制解释和本站判断分开，不把定性一致写成机制证明。</li></ol></section>
 {report.papers.map((p,i)=>{const fig=figures[p.title];return <section className="paper-detail" id={'paper-'+(i+1)} key={p.title}><div className="paper-kicker"><span>{String(i+1).padStart(2,'0')} · {p.category}</span><b>{p.access.includes('全文精读')?'全文精读':'摘要级'} · 推荐 {p.rating}</b></div><h2>{p.material}｜{p.title}</h2><div className="tag-row">{p.tags.map(t=><span key={t}>{t}</span>)}</div><div className="meta-grid"><div className="meta-item"><span>来源</span><b>{p.journal}</b></div><div className="meta-item"><span>日期</span><b>{p.date}</b></div><div className="meta-item"><span>生长 / 方法</span><b>{p.method}</b></div><div className="meta-item"><span>作者</span><b>{p.authors}</b></div><div className="meta-item institution-item"><span>主要单位</span><b>{p.institutions}</b></div></div><p className="links"><a href={p.doi}>DOI / arXiv ↗</a>{p.fullText&&p.fullText!==p.doi&&<a href={p.fullText}> 公开全文 ↗</a>}</p><p className="version-note"><b>版本与阅读范围：</b>{p.versionNote} {p.access}</p><div className="paper-conclusion"><span>CONCLUSION</span><h3>这篇论文讲了什么故事</h3><p>{p.conclusion}</p></div>{fig&&<figure className="data-figure"><figcaption><b>{fig.title}</b><span>根据公开正文数值重绘，并非论文原图</span></figcaption><img className="report-figure-image" src={fig.src} alt={fig.title}/><p className="figure-analysis"><b>图解分析：</b>{fig.caption}</p></figure>}{p.sections.map(s=><div key={s.title}><h3>{s.title}</h3>{s.text.split('\n\n').map((part,j)=><p key={j}>{part}</p>)}</div>)}<div className="reading-guide"><span>{p.readingGuide.priority}</span><h3>本篇专属阅读路径</h3><p><b>先读：</b>{p.readingGuide.first}</p><p><b>重点：</b>{p.readingGuide.focus}</p><p><b>下一步：</b>{p.readingGuide.next}</p></div></section>})}
 <section className="comparison" id="compare"><p className="eyebrow">TODAY AT A GLANCE</p><h2>材料、方法与证据状态</h2><div className="table-wrap"><table><thead><tr><th>材料</th><th>方法</th><th>核心物性/问题</th><th>全文状态</th><th>推荐</th></tr></thead><tbody>{report.papers.map(p=><tr key={p.title}><td>{p.material}</td><td>{p.method}</td><td>{p.conclusion.slice(0,72)}…</td><td>{p.access.includes('全文精读')?'全文精读':'摘要级'}</td><td>{p.rating}</td></tr>)}</tbody></table></div><h3>板块统计</h3><p>{Object.entries(counts).map(([k,v])=>`${k} ${v}篇`).join('；')}。正式期刊{formal}篇，arXiv独立稿{report.papers.length-formal}篇；全文精读{full}篇，摘要级{report.papers.length-full}篇。</p></section>
 <section className="search-note" id="search-log"><p className="eyebrow">SEARCH LOG</p><h2>逐轨检索、访问与去重记录</h2><p><b>实际时间窗：</b>{report.searchWindow}</p>{report.searchTerms.map(x=><p key={x}>{x}</p>)}</section></article></div></main>;
}

