/* eslint-disable @next/next/no-html-link-for-pages */
import type { Metadata } from 'next';
import report from '../../../content/reports/2026-09-01.json';

export const metadata:Metadata={title:'2026-09-01 简报｜晶体生长和物性调控',description:'七篇生长—缺陷—物性证据链：超导膜、界面轨道、晶相量子点与短程有序。'};
const ids=['zrnx','tin','nno-nmo','algaas','ptsige','yig','gesn'];
function ProcessFigure(){return <div className="figure-block dark"><div className="cvt-figure"><div className="ampoule"><span className="source-zone">生长参数<small>温度 · 气氛 · 界面</small></span><i>→ 结构与缺陷 →</i><span className="growth-zone">物性读出<small>输运 · 光谱 · 微波</small></span></div><div className="time-line"><span>直接观察</span><b>模型拟合 / 作者推断</b><span>复现建议</span></div></div><p><b>图解｜本期统一证据链。</b>根据七篇论文的方法与结果原创重绘，并非论文原图。网站逐篇区分直接观察、模型拟合和机制推断，避免把相关性写成因果结论。</p></div>}

export default function Report(){return <main className="report-page"><header className="site-header"><a className="brand" href="/"><span className="brand-mark">晶</span><span>晶体生长和物性调控</span></a><nav><a className="active" href="/reports/2026-09-01">今日简报</a><a href="/archive">往期归档</a><a href="/search">文献检索</a></nav><div className="live-chip"><span/> 每日 08:00 更新</div></header>
<div className="report-hero"><div><p className="eyebrow">DAILY REPORT · ISSUE 007</p><h1>晶体生长与物性<br/>文献简报</h1><p>2026 年 9 月 1 日 · 北京时间</p></div><div className="report-summary"><b>今日判断</b><p>{report.hotspot}</p><div><span>7 篇入选</span><span>7 篇全文详读</span><span>2 篇重要修订</span></div></div></div>
<div className="report-layout"><aside className="report-toc"><p>本期目录</p>{report.papers.map((paper,i)=><a key={paper.title} href={`#${ids[i]}`}>{String(i+1).padStart(2,'0')} · {paper.material}</a>)}<a href="#compare">汇总对比</a><a href="#search">检索记录</a></aside><article className="report-content">
<section className="report-lede"><p className="eyebrow">TODAY&apos;S SIGNAL</p><h2>今日要点</h2><ol><li><b>超导膜的关键变量从“是否结晶”推进到“缺陷怎样组织临界行为”。</b>ZrNₓ 以氮含量连续调节无序，TiN 则用表面重构减少马赛克度，但器件 Q 并未同步提高。</li><li><b>界面和局域结构正在成为独立调控轴。</b>NdNiO₃/NdMnO₃ 的界面轨道反转、AlGaAs 的晶相插层、GeSn 的 Sn–Sn 近邻都证明宏观成分不足以预测物性。</li><li><b>器件读出是材料评价的必要闭环。</b>PtSiGe 的 flip-chip 与真实谐振器结果并不完全一致，YIG 网络则把单晶低阻尼直接转化为 30 dB 读出裕量。</li></ol><ProcessFigure/></section>
{report.papers.map((paper,index)=><section className="paper-detail" id={ids[index]} key={paper.title}><div className="paper-kicker"><span>{String(index+1).padStart(2,'0')}</span><b>{paper.access} · 推荐 {paper.rating}</b></div><h2>{paper.material}：{paper.title}</h2><p className="english-title">{paper.title}</p><div className="meta-grid"><div className="meta-item"><span>来源</span><b>{paper.journal}</b></div><div className="meta-item"><span>日期</span><b>{paper.date}</b></div><div className="meta-item"><span>生长/方法</span><b>{paper.method}</b></div><div className="meta-item"><span>作者</span><b>{paper.authors}</b></div></div><p className="links"><a href={paper.doi}>arXiv 条目 ↗</a><a href={paper.fullText}>公开全文 ↗</a></p>{paper.sections.map(section=><div key={section.title}><h3>{section.title}</h3><p>{section.text}</p></div>)}</section>)}
<section className="comparison" id="compare"><p className="eyebrow">COMPARISON</p><h2>本期汇总</h2><div className="table-wrap"><table><thead><tr><th>材料 / 样品</th><th>生长 / 方法</th><th>核心物性</th><th>全文状态</th><th>推荐</th></tr></thead><tbody>{report.papers.map(p=><tr key={p.title}><td>{p.material}</td><td>{p.method}</td><td>{p.sections[3].text.slice(0,92)}…</td><td>{p.access}</td><td>{p.rating}</td></tr>)}</tbody></table></div></section>
<section className="search-note" id="search"><p className="eyebrow">SEARCH LOG</p><h2>检索、全文访问与去重</h2><p><b>实际时间窗：</b>{report.searchWindow}</p><p><b>检索词：</b>{report.searchTerms.join('；')}。</p><p><b>站点：</b>arXiv cond-mat/new、arXiv abstract/HTML/PDF，并核查 Physical Review 系列、Nature 系列、Advanced Materials、Nano Letters 的时间窗结果。7 篇均实际读取公开正文；TiN 与 GeSn 为重要新修订，其新增原因已逐篇说明。</p><p><b>去重：</b>排除 8 月 31 日已精读的 YbNi₄P₂、La₃Ni₂O₇ 与 MoS₂。近三日没有新的未重复重费米子条目；没有用更早、无更新的论文填充。检索时间：2026-09-01（北京时间）。</p></section>
</article></div></main>}
