/* eslint-disable @next/next/no-html-link-for-pages, @next/next/no-img-element */
import type {Metadata} from 'next';
import report from '../../../content/reports/2026-09-21.json';

export const metadata:Metadata={title:'2026-09-21 简报｜每日文献简报',description:report.headline};

const figures:Record<string,{src:string;title:string;caption:string}>= {
  'Electrical injection of meron-antimeron pairs into a magnetic domain wall':{src:'/reports/2026-09-21/meron-injection.svg',title:'原创图解 1｜梯形磁条中的meron–antimeron电注入',caption:'依据npj Spintronics公开正文与Methods重绘。20 ns脉冲、平均电流密度4.26×10¹¹ A/m²把成对纹理注入畴壁；+12/−9 Oe的极性依赖湮灭场支持拓扑配对，但成像分辨率仍限制单个纹理内部结构的直接判定。'},
  'Intrinsic Fermi Level Pinning and Reversible Depinning at Ultralow-Defect Epitaxial MoSe2/Au(111) Interfaces':{src:'/reports/2026-09-21/mose2-pinning.svg',title:'原创图解 2｜MoSe₂/Au(111)内禀钉扎与可逆解钉扎',caption:'依据Nano Letters出版社摘要公开数值重绘。约1.7×10¹⁰ cm⁻²的超低缺陷密度仍出现钉扎，使“缺陷态主导”解释不足；Se插层带来的可逆解钉扎更支持MIGS与界面偶极机制。正文未取得，能带位置与制备窗口仍需复核。'},
  'Interfacial Control of Hot-Carrier Extraction and Photostability in Two-Dimensional Materials':{src:'/reports/2026-09-21/ws2-interface.svg',title:'原创图解 3｜WS₂/Au界面形貌与亚100 fs抽取',caption:'依据ACS Nano正式版对应公开稿arXiv:2605.07921v1重绘。平滑Au上电子/空穴抽取为60/50 fs，粗糙Au上为135/90 fs；后者因电子—空穴不对称更强产生更大的净瞬态电流，说明“更快”不等于“更强”。'}
};
export default function Report(){
 const full=report.papers.filter(p=>p.access.includes('全文精读')).length;
 const counts=report.papers.reduce<Record<string,number>>((m,p)=>(m[p.category]=(m[p.category]||0)+1,m),{});
 return <main className="report-page">
 <header className="site-header"><a className="brand" href="/"><span className="brand-mark">文</span><span>每日文献简报</span></a><nav aria-label="主导航"><a className="active" href="/reports/2026-09-21">今日简报</a><a href="/materials">材料时间线</a><a href="/search">智能检索</a><a href="/weekly">本周趋势</a><a href="/workspace">我的研究</a><a href="/archive">归档</a></nav><div className="live-chip"><span/> 每日 10:00 更新</div></header>
 <div className="report-hero"><div><p className="eyebrow">DAILY REPORT · ISSUE 027</p><h1>每日文献简报</h1><p>2026 年 9 月 21 日 · 北京时间</p></div><div className="report-summary"><b>今日判断</b><p>{report.headline}</p><div><span>{report.papers.length} 篇入选</span><span>{full} 篇全文精读</span><span>正式期刊 8 篇</span></div></div></div>
 <div className="report-layout"><aside className="report-toc"><p>本期目录</p>{report.papers.map((p,i)=><a key={p.title} href={'#paper-'+(i+1)}>{String(i+1).padStart(2,'0')} · {p.material.slice(0,14)}</a>)}<a href="#compare">板块统计</a><a href="#search-log">检索日志</a></aside><article className="report-content">
 <section className="report-lede"><p className="eyebrow">TODAY&apos;S SIGNAL</p><h2>今日要点与访问边界</h2><p>{report.hotspot}</p><ol><li><b>三日回溯：</b>9月21日当天核心来源零高相关新增，arXiv周一列表在北京时间中午尚未释放，实际检索窗口为9月19–21日。</li><li><b>正式期刊优先：</b>8篇均为此前未进入站内的正式期刊延迟索引论文；独立arXiv新增为0。</li><li><b>阅读等级：</b>2篇全文精读、6篇仅摘要/元数据；其余正文直链均返回403，且未检测到可复用的浙大机构会话。</li><li><b>图解合规：</b>三张图依据公开正文或摘要数值原创重绘；不复用受限论文图片，并明确每张图不能证明的边界。</li></ol></section>
 {report.papers.map((p,i)=>{const fig=figures[p.title];return <section className="paper-detail" id={'paper-'+(i+1)} key={p.title}><div className="paper-kicker"><span>{String(i+1).padStart(2,'0')} · {p.category}</span><b>{p.access.includes('全文精读')?'全文精读':p.access.includes('正文核查')?'正文核查':'摘要级'} · 推荐 {p.rating}</b></div><h2>{p.material}｜{p.title}</h2><div className="tag-row">{p.tags.map(t=><span key={t}>{t}</span>)}</div><div className="meta-grid"><div className="meta-item"><span>来源</span><b>{p.journal}</b></div><div className="meta-item"><span>上线日期</span><b>{p.date}</b></div><div className="meta-item"><span>生长 / 方法</span><b>{p.method}</b></div><div className="meta-item"><span>作者</span><b>{p.authors}</b></div><div className="meta-item institution-item"><span>主要单位</span><b>{p.institutions}</b></div></div><p className="links"><a href={p.doi}>DOI / 原文 ↗</a>{p.fullText&&<a href={p.fullText}> 公开全文 ↗</a>}</p><p className="version-note"><b>版本与阅读范围：</b>{p.versionNote} {p.access}</p><div className="paper-conclusion"><span>CONCLUSION</span><h3>这篇论文讲了什么故事</h3><p>{p.conclusion}</p></div>{fig&&<figure className="data-figure"><figcaption><b>{fig.title}</b><span>根据公开Methods与正文数值重绘，并非论文原图</span></figcaption><img className="report-figure-image" src={fig.src} alt={fig.title}/><p className="figure-analysis"><b>图解分析：</b>{fig.caption}</p></figure>}{p.sections.map(s=><div key={s.title}><h3>{s.title}</h3>{s.text.split('\n\n').map((part,j)=><p key={j}>{part}</p>)}</div>)}<div className="reading-guide"><span>{p.readingGuide.priority}</span><h3>本篇专属阅读路径</h3><p><b>先读：</b>{p.readingGuide.first}</p><p><b>重点：</b>{p.readingGuide.focus}</p><p><b>下一步：</b>{p.readingGuide.next}</p></div></section>})}
 <section className="comparison" id="compare"><p className="eyebrow">TODAY AT A GLANCE</p><h2>板块与全文状态</h2><div className="table-wrap"><table><thead><tr><th>研究板块</th><th>篇数</th></tr></thead><tbody>{Object.entries(counts).map(([k,v])=><tr key={k}><td>{k}</td><td>{v}</td></tr>)}</tbody></table></div><p>正式期刊8篇；arXiv独立新稿0篇；全文精读2篇；仅摘要/元数据6篇。各篇生长方法、关键物性、证据边界和专属阅读路线见上方分篇分析。</p></section>
 <section className="search-note" id="search-log"><p className="eyebrow">SEARCH LOG</p><h2>逐轨检索、访问与去重记录</h2><p><b>时间窗：</b>{report.searchWindow}</p>{report.searchTerms.map(x=><p key={x}>{x}</p>)}</section>
 </article></div></main>;
}

