/* eslint-disable @next/next/no-html-link-for-pages, react/no-unescaped-entities */
import type { Metadata } from 'next';

export const metadata:Metadata={title:'2026-08-29 简报｜晶体生长和物性调控',description:'KTa₁₋ₓNbₓO₃ 室温塑性、NiPS₃ 太赫兹激发与 Si/SiGe 氧杂质工程。'};
const Meta=({label,children}:{label:string,children:React.ReactNode})=><div className="meta-item"><span>{label}</span><b>{children}</b></div>;

export default function Report(){return <main className="report-page">
  <header className="site-header"><a className="brand" href="/"><span className="brand-mark">晶</span><span>晶体生长和物性调控</span></a><nav><a className="active" href="/reports/2026-08-29">今日简报</a><a href="/archive">往期归档</a><a href="/search">文献检索</a></nav><div className="live-chip"><span/> 每日 08:00 更新</div></header>
  <div className="report-hero"><div><p className="eyebrow">DAILY REPORT · ISSUE 004</p><h1>晶体生长与物性<br/>文献简报</h1><p>2026 年 8 月 29 日 · 北京时间</p></div><div className="report-summary"><b>今日判断</b><p>当天没有新的 arXiv 批次，因此按规则回溯三日。本期没有可复现的 Flux/CVT 新配方，热点集中在“缺陷如何被制造、识别并转化为物性”。</p><div><span>3 篇入选</span><span>3 篇全文精读</span><span>0 篇重复</span></div></div></div>
  <div className="report-layout"><aside className="report-toc"><p>本期目录</p><a href="#ktn">01 · KTN</a><a href="#nips3">02 · NiPS₃</a><a href="#sige">03 · Si/SiGe</a><a href="#compare">汇总对比</a><a href="#search">检索记录</a></aside><article className="report-content">
    <section className="report-lede"><p className="eyebrow">TODAY'S SIGNAL</p><h2>今日要点</h2><ol><li><b>首要推荐 KTa₁₋ₓNbₓO₃。</b>论文建立“压痕筛选—宏观压缩—原子尺度位错观察”闭环，说明固溶体能扩展室温可塑氧化物材料族。</li><li><b>NiPS₃ 的价值在谱学判据。</b>偏振和温度两个正交变量把约 1.07 THz 磁振子与约 0.65 THz 折叠声子分开，但低温介电背景假设仍需独立验证。</li><li><b>Si/SiGe 给出最干净的工艺因果对照。</b>6 nm 埋置 Si 层使氧背景下降约 5–6 倍、迁移率提高约 11%，同时低密度输运指标基本不变。</li></ol></section>

    <section className="paper-detail" id="ktn"><div className="paper-kicker"><span>01</span><b>全文精读 · 推荐 S</b></div><h2>KTa₁₋ₓNbₓO₃：用固溶体扩展室温可塑钙钛矿</h2><p className="english-title">A solid-solution approach for room-temperature bulk plasticity in KTa1-xNbxO3</p><div className="meta-grid"><Meta label="来源">arXiv:2608.26678v1</Meta><Meta label="提交">2026-08-27</Meta><Meta label="方法">熔体慢冷 / Czochralski</Meta><Meta label="全文范围">正文、Methods、图1–4</Meta></div><p className="links"><a href="https://arxiv.org/abs/2608.26678">arXiv 条目 ↗</a><a href="https://arxiv.org/pdf/2608.26678">PDF 全文 ↗</a></p>
      <h3>问题—假设—实验闭环</h3><p>位错工程已经能改变钙钛矿氧化物的铁电、催化与力电响应，但能够在室温、块体尺度先发生位错滑移而不是脆断的材料极少。作者从两个已知端元出发：KTaO₃ 在 &lt;001&gt; 压缩下约 270 MPa 屈服，KNbO₃ 约 60 MPa。Ta⁵⁺ 与 Nb⁵⁺同价且离子半径都约 0.78 Å，因此工作假设是 KTa₁₋ₓNbₓO₃ 固溶体不会产生强烈的经典尺寸失配强化，仍可在室温激活位错。</p><p>设计不是只展示一个压痕。第一步用 Brinell 压痕/划擦快速寻找有塑性区而非纯裂纹的成分；第二步用 &lt;001&gt; 单轴压缩取得宏观应力—应变与屈服；第三步从划痕内部用 FIB 提取薄片，以 ABF-STEM 直接观察位错。形貌、宏观力学和原子尺度证据依次排除“表面损伤看起来像滑移”“只有局部塑性”“条纹只是铁电畴”的替代解释。</p>
      <h3>晶体、结构和生长信息</h3><p>名义组分覆盖 x=0.1、0.175、0.3、0.4、0.5。x=0.1、0.175、0.3 样品由熔体慢冷法制备并来自 Oak Ridge National Laboratory；x=0.3、0.4、0.5 由作者之一采用 Czochralski 法生长。两条来源在 x=0.3 重叠，能检查结论是否只属于一个供应商。低于约 x=0.4 的样品室温为立方相，x=0.5 为四方铁电相。实验前磨削并精抛到镜面。</p><p><b>复现边界：</b>本文未报告原料纯度、K/Ta/Nb 起始配比、熔体补偿策略、坩埚材质、气氛、峰值温度、慢冷速率、提拉/旋转速度、退火或淬火、样品尺寸、取向误差与产率。论文引用早期晶体生长文献，但不能据此把旧配方当成本批次参数。它适合指导样品筛选与力学验证，不足以直接复制晶体生长。</p>
      <div className="figure-block"><div className="cvt-figure"><div className="ampoule"><span className="source-zone">压痕 / 划擦<small>2.5 mm 球 · 1 kgf</small></span><i>证据尺度 →</i><span className="growth-zone">ABF-STEM<small>200 kV · FIB 薄片</small></span></div><div className="time-line"><span>表面塑性区</span><b>&lt;001&gt; 压缩</b><span>位错直接成像</span></div></div><p><b>图解 1｜验证闭环。</b>根据论文 Methods 重绘，并非论文原图。其关键不是某一张显微图，而是三个尺度观察指向同一位错滑移机制。</p></div>
      <h3>测量条件、关键结果和证据强弱</h3><p>Brinell 压痕使用 2.5 mm 硬化钢球，载荷 1.0 kgf、保持 10 s；划痕同为 1 kgf，可形成约 2 mm 轨迹，10 次往复用于制造高位错密度区。激光共焦显微镜看到 (001) 表面横纵交叉的滑移迹线，对应 {110}&lt;110&gt; 系。KTN0.5 同时出现条带状铁电畴及压痕附近畴碎裂，说明位错—畴壁耦合确实存在；但立方 KTN0.175、KTN0.3 没有畴，仍出现同样滑移迹线，因此畴翻转不能解释共同的塑性表征。</p><p>宏观压缩沿 &lt;001&gt;、应变率约 10⁻⁴ s⁻¹。端面加 0.5 mm 退火铜箔以缓解泊松膨胀造成的摩擦应力；这也带来曲线起始的非线性“软化”，作者认为会平移塑性应变量、但不明显改变屈服应力。KTN0.3 屈服约 300 MPa，Schmid 因子 0.5 对应 CRSS 约 150 MPa。压痕塑性区直径约 140 μm，以赫兹接触估算最大剪应力约 320 MPa，只能作为晶格摩擦上限，而非精确屈服值。10 次划擦后 ABF-STEM 给出约 10¹⁴ m⁻² 位错密度，这是排除纯裂纹模型的最强直接证据。</p>
      <h3>本简报判断、局限和下一批实验</h3><p><b>直接观察：</b>滑移迹线、宏观塑性段、TEM 位错。<b>模型计算：</b>赫兹剪应力与 Schmid 分解。<b>作者推断：</b>所有 0&lt;x&lt;1 组成原则上都可能室温可塑。后者超出了实际测试的 x≤0.5 范围，且 KTN0.3 生长前就有不明水平条带，可能钉扎位错并把屈服推到高于两个端元的约 300 MPa。因此“固溶体路线有效”证据强，“不存在固溶强化”则仍弱。</p><p>建议下一批晶体在同一生长平台完成 x 梯度，使用 WDS/ICP 测实际 Nb、K 挥发与氧空位，Laue 定向后记录初始位错密度、条带缺陷和畴结构。力学上应同时报告试样长宽比、端面平行度、卸载回线和多根样品统计。若目标是位错调控铁电性，应优先比较 x≈0.4 两侧立方—四方边界，寻找位错滑移与畴壁响应的耦合窗口。</p><p><b>阅读建议：</b>先看图 2–4 的三尺度闭环，再读 Methods 中端面铜箔和取样方式。推荐 S；对缺陷工程很强，对生长配方的直接价值有限。</p>
    </section>

    <section className="paper-detail" id="nips3"><div className="paper-kicker"><span>02</span><b>全文精读 · 推荐 A+</b></div><h2>NiPS₃：以偏振和温度分离磁振子与折叠声子</h2><p className="english-title">Magnetic permeability and zone-folded phonons in layered NiPS3</p><div className="meta-grid"><Meta label="来源">arXiv:2608.26405v1</Meta><Meta label="提交">2026-08-26</Meta><Meta label="结构">单斜 C2/m</Meta><Meta label="许可">CC BY-NC-ND 4.0</Meta></div><p className="links"><a href="https://arxiv.org/abs/2608.26405">arXiv 条目 ↗</a><a href="https://arxiv.org/html/2608.26405">HTML 全文 ↗</a></p>
      <h3>为什么两个太赫兹峰容易混淆</h3><p>NiPS₃ 是 Néel 温度约 155 K 的层状 XY 反铁磁 Mott 绝缘体。磁有序既允许低能磁振子，又会通过磁结构放大晶胞、把原本位于区边界的声子折回 Γ 点，因此两类激发都可能落在太赫兹窗口并随有序增强。作者提出两个判据：磁振子应服从 THz 磁场相对晶轴的选择定则，并随降温体现交换/各向异性增强；折叠声子则主要由电场耦合，频率对温度较稳但强度可随结构/磁序增长。</p>
      <h3>样品、生长信息与质量判断</h3><p>测量使用约 450 μm 厚的块状片晶。室温 Raman 用 633 nm 激光观察到 8 个模，XRD 与单斜 C2/m 结构一致且衍射峰尖锐。可访问正文没有交代晶体的生长路线；原料纯度、化学计量、Flux/CVT 选择、助熔剂或输运剂、安瓿、温区、温程、持续时间、降温速率、分离/退火、晶体横向尺寸与产率均为“正文未报告”。EDS/WDS/ICP、Laue、层错/空位、不同批次统计也未报告。XRD 与 Raman 能支撑相和振动模归属，却不足以建立缺陷化学或绝对晶向的质量链。</p>
      <h3>测量几何和定量参数</h3><p>THz-TDS 使用 780 nm、约 130 fs、76 MHz Ti:sapphire 激光驱动有偏置光电导天线；样品在低温恒温器中常入射，系统保持相对湿度低于 5%。0° 几何表示 THz 磁场平行 b 轴，旋转到 90° 改变选择定则。作者从 144 K 降至 13 K，并以 300 K 响应构造介电背景。0° 下的模式随降温蓝移，在 13 K 到约 1.07 THz；90° 下约 0.65 THz 模频率近乎不变而振幅增长。两种正交演化分别对应磁振子与区折叠声子。</p><p>在假定 ε(13 K)≈ε(300 K) 后，作者从复透射反演磁导率，并用 Drude–Lorentz 模型拟合 13 K 磁响应：ω₀=1.0598±0.0018 THz，线宽 0.2524±0.0071 THz，Δμ=(3.497±0.094)×10⁻²。窄小的拟合误差反映参数在该模型内稳定，并不自动证明介电背景假设正确。</p>
      <div className="figure-block dark"><div className="node-figure"><div className="frequency-lines"><span/><span/></div><div className="node-ring"><i/><i/><i/><i/></div></div><p><b>图解 2｜双判据分离。</b>根据论文结果重绘，并非论文原图。上支随降温蓝移且只在特定磁场偏振出现，是磁性证据；下支频率稳定、强度随有序增强，更符合折叠声子。</p></div>
      <h3>证据边界、替代解释与建议</h3><p><b>直接观察：</b>两种偏振下的透射峰和温度演化。<b>模型拟合：</b>复磁导率的 Lorentz 参数。<b>作者推断：</b>1.07 THz 为磁振子、0.65 THz 为区折叠声子。最强环节是偏振与温度两个相互独立的判据指向同一归属；最弱环节是把 300 K 介电函数当作 13 K 背景。若低温声子或折射率显著变化，磁导率中会混入电偶极响应。</p><p>复现时应增加同一晶体的低温反射或时域内部回波，独立约束 ε(ω) 与厚度；用 Laue 给出 b 轴取向误差，并在多片不同厚度样品上验证峰位。生长组若希望关联缺陷与线宽，需要补上实际生长批次、S/P 化学计量、层错/TEM 与面内成分映射。推荐 A+；先读选择定则和反演方法，再核查补充的光路与背景假设。</p>
    </section>

    <section className="paper-detail" id="sige"><div className="paper-kicker"><span>03</span><b>全文精读（含 SI）· 推荐 A+</b></div><h2>Si/SiGe：用 6 nm Si 捕获层切断氧杂质与迁移率</h2><p className="english-title">Mobility Enhancement in Si/SiGe Quantum Well Enabled by a Buried Si Layer Trapping Oxygen Impurities</p><div className="meta-grid"><Meta label="来源">arXiv:2608.27377v1</Meta><Meta label="提交">2026-08-27</Meta><Meta label="方法">200 mm RP-CVD</Meta><Meta label="样本量">1.5 K 各 7 器件</Meta></div><p className="links"><a href="https://arxiv.org/abs/2608.27377">arXiv 条目 ↗</a><a href="https://arxiv.org/html/2608.27377">HTML 全文与 SI ↗</a></p>
      <h3>工艺因果问题和四结构对照</h3><p>量子计算用 Si/SiGe 量子阱要求低无序二维电子气，但氧既可能在 Si/SiGe 温度切换时形成局部峰，也可能作为 SiGe 生长中的背景杂质。作者设计四种结构，交叉改变 Si 量子阱/捕获层温度（600 或 700 °C）和是否增加 6 nm 埋置 Si 层。SIMS 先回答“温度切换产生峰”和“Si 生长步骤降低后续背景”这两个不同问题；输运则只比较同为 600 °C 的无捕获层/有捕获层结构，从而避免把温度序列差异误归因于氧。</p>
      <h3>生长、器件和成分剖面</h3><p>全部异质结构在 200 mm p 型 Si(100) 晶圆上，以硅烷和锗烷为前驱体进行减压 CVD。700 °C Si 量子阱夹在 600 °C SiGe 势垒时，下势垒氧背景约 7×10¹⁷ cm⁻³，量子阱附近峰约 5×10¹⁸ cm⁻³；把 Si 与 SiGe 都设为 600 °C 后，尖锐氧峰被抑制。6 nm Si 捕获层在两种温度序列中都把随后生长 SiGe 的氧从约 4×10¹⁷ 降到 7–8×10¹⁶ cm⁻³，说明作用来自 Si 生长步骤本身而非只来自升温。用于输运的 600 °C 两结构在量子阱附近分别约 1×10¹⁸ 与 1.3×10¹⁷ cm⁻³。</p><p>器件为宽 20 μm、压探针间距 300 μm 的 Hall-bar FET。欧姆接触采用 P 离子注入 4.5×10¹⁵ cm⁻²、20 keV，随后 700 °C 激活 1 min；栅介质为 300 °C 沉积的 10 nm HDP-SiO₂，顶栅为 30 nm TiN。正文仍未报告反应腔压、前驱体流量、Ge 分数完整梯度、总厚度、温度切换时间、升降温速率、晶圆内均匀性和产率。</p>
      <h3>SIMS 与低温输运怎样接起来</h3><p>SIMS 使用 ADEPT 1010、Cs 一次离子，同时监测 ¹⁶O、⁷⁰Ge、³⁰Si，约 50 μm 束斑；溅射坑用轮廓仪标深，SiGe 参比经 RBS 标定，并用 PCOR-SIMS 随局部 Ge 含量修正灵敏度和溅射速率。这比简单比较未校正的氧计数更可靠。1.5 K 测量在 Teslatron-PT，0.3–1.5 K 在 Kiutra L-Type；电流≤50 nA，17 Hz 四探针锁相，垂直磁场从 −5 到 305 mT。Hall 斜率给密度，低密度电导以 σ∝(n−nₚ)^t 拟合渗流阈值，迁移率标度用局域对数导数 α(n)=dlogμ/dlogn，避免任意选一个宽密度区间。</p><p>1.5 K 下两组各 7 个器件。低氧组的最大中位迁移率约 4.8×10⁵ cm²V⁻¹s⁻¹，高氧组约 4.3×10⁵，提高约 11%；差异主要在较高密度出现。两组渗流密度分布和 α(n) 基本重合。代表性器件从 1.5 K 冷至 0.3 K 后，迁移率最大值位置从约 3.8×10¹¹ 移到 2.8×10¹¹ cm⁻²，分数增益在约 1×10¹¹ cm⁻² 最大，但高氧/低氧器件的分数增益和 α(n) 仍相近。</p>
      <div className="figure-block"><div className="cvt-figure"><div className="ampoule"><span className="source-zone">SiGe：高氧背景<small>≈4×10¹⁷ cm⁻³</small></span><i>6 nm Si trap →</i><span className="growth-zone">后续 SiGe<small>7–8×10¹⁶ cm⁻³</small></span></div><div className="time-line"><span>氧降低 5–6×</span><b>μ +11%</b><span>nₚ、α(n) 近似不变</span></div></div><p><b>图解 3｜工艺—杂质—输运证据链。</b>根据正文与 SI 重绘，并非论文原图。氧大幅下降只带来迁移率幅值上移，没有改变低密度标度，这是结论的关键边界。</p></div>
      <h3>因果强度、局限与下一轮设计</h3><p><b>直接观察：</b>SIMS 氧剖面、Hall/纵向电压。<b>拟合量：</b>迁移率、nₚ 与 α(n)。<b>作者推断：</b>氧限制高密度动量弛豫，却不是低密度长程势涨落的主导源。五到八倍氧差与 14 个器件统计使前半句较强；后半句依赖“其他缺陷没有同步变化”，且 0.3 K 只展示代表性器件，证据稍弱。SIMS 是局部测量，尚不能排除晶圆尺度不均匀或捕获层引入的应变/界面改变。</p><p>建议增加同片多点 SIMS、全晶圆迁移率映射与盲法器件统计；用受控氧剂量或原位残余气体分析建立剂量—响应曲线；把捕获层厚度和到量子阱距离作为正交变量，并用 TEM/XRD 检查其是否改变错配位错和界面粗糙度。推荐 A+；对“如何用外延结构主动吸收杂质”非常实用，阅读顺序应先看图 1 的四结构控制，再看图 2/3 与 SI 的原始器件离散度。</p>
    </section>

    <section className="comparison" id="compare"><p className="eyebrow">COMPARISON</p><h2>本期汇总</h2><div className="table-wrap"><table><thead><tr><th>材料 / 结构</th><th>生长</th><th>关键窗口</th><th>核心物性</th><th>全文 / 推荐</th></tr></thead><tbody><tr><td>KTa₁₋ₓNbₓO₃<br/>立方→四方</td><td>慢冷 / Czochralski</td><td>本文未给温程</td><td>σy≈300 MPa；ρdis≈10¹⁴ m⁻²</td><td>全文 · S</td></tr><tr><td>NiPS₃<br/>C2/m</td><td>正文未报告</td><td>450 μm 片晶</td><td>1.06 THz 磁振子；0.65 THz 声子</td><td>全文 · A+</td></tr><tr><td>Si/SiGe QW<br/>外延异质结构</td><td>200 mm RP-CVD</td><td>600 °C；6 nm Si trap</td><td>氧↓5–6×；μ↑11%</td><td>全文+SI · A+</td></tr></tbody></table></div></section>
    <section className="search-note" id="search"><p className="eyebrow">SEARCH LOG</p><h2>检索、访问与去重</h2><p>检索日期：2026-08-29（北京时间）。当天为周六，arXiv 没有新的当日批次，因此按规则回溯 2026-08-27—2026-08-29；入选稿件实际提交于 8 月 26–27 日，并进入 8 月 28 日 new listing。检索 arXiv cond-mat 新列表、全文 HTML/PDF 与作者提供的 SI；同时核对 Nature、APS 与关键词检索。检索词包括 crystal growth、single crystal、flux、CVT、dislocation plasticity、Si/SiGe oxygen mobility、NiPS3 THz。按 DOI、arXiv ID 和题目与 8 月 28 日归档去重，0 篇重复。</p><p>全文状态：3 篇均实际读取正文与 Methods；Si/SiGe 同时读取嵌入式 Supporting Information；KTN 当前未见独立 SI；NiPS₃ 许可为 CC BY-NC-ND 4.0，因此本站只提供原创示意，不改编论文图。检索期内未发现同时满足“新增、Flux/CVT、单晶生长参数充分、含物性测量”的论文，故没有用更早条目凑数。</p></section>
  </article></div>
</main>}
