/* eslint-disable @next/next/no-html-link-for-pages, @next/next/no-img-element */
import type {Metadata} from 'next';
import report from '../../../content/reports/2026-09-29.json';

export const metadata:Metadata={title:'2026-09-29 简报｜每日文献简报',description:report.headline};
const figures:Record<string,{src:string;title:string;caption:string}>={
 'Growth and Interface Engineering of Superconducting TiN on Sapphire by Thermal-Laser Epitaxy':{src:'/reports/2026-09-29/tin-growth.svg',title:'TiN：两步生长把界面保护与高温结晶拆开',caption:'图中温度 850/1150 °C、种子层 4–5 nm、最终约 75 nm 取自 Methods；RRR 9.7→12.2 是不同生长方案的输运比较，不代表只由种子层厚度一个变量决定。来源：arXiv:2609.31721；根据公开正文数值原创重绘，并非论文原图。'},
 'The stripe state at 1/8 Ba doping hosts optimal superconductivity in La-214 cuprates under low in-plane stress':{src:'/reports/2026-09-29/lbco-stress.svg',title:'LBCO 1/8：不同超导温度判据的应力响应',caption:'横轴为面内单轴压应力，标出的 0、0.23、0.56 GPa 与 3–5、35、37、46 K 来自作者公开稿 Fig.2–4 及正文；不同符号是 AC 磁化率中点、面内零电阻、转变起始，不能混作同一个体 Tc。根据公开数值原创重绘，并非论文原图。'},
 'Enhanced sliding in the coexisting Charge Density Wave phase of strained TbTe3':{src:'/reports/2026-09-29/tbte3-sliding.svg',title:'TbTe₃：共存区扩展短程关联温域',caption:'纵轴 T′/Tc−1：单 CDW 约 0.07、a/c≈1 共存区约 0.22，取自正文 Fig.8 及讨论；这是阈值外推的模型量，不是直接测到的短程有序长度。根据公开正文数值原创重绘，并非论文原图。'}
};
export default function Report(){
 const full=report.papers.filter(p=>p.access.includes('全文精读')).length;
 const formal=report.papers.filter(p=>p.tags.includes('正式期刊')).length;
 const counts=report.papers.reduce<Record<string,number>>((m,p)=>(m[p.category]=(m[p.category]||0)+1,m),{});
 return <main className="report-page"><header className="site-header"><a className="brand" href="/"><span className="brand-mark">文</span><span>每日文献简报</span></a><nav aria-label="主导航"><a className="active" href="/reports/2026-09-29">今日简报</a><a href="/materials">材料时间线</a><a href="/search">智能检索</a><a href="/weekly">本周趋势</a><a href="/workspace">我的研究</a><a href="/archive">归档</a></nav><div className="live-chip"><span/> 每日更新</div></header>
 <div className="report-hero"><div><p className="eyebrow">DAILY REPORT · ISSUE 035</p><h1>每日文献简报</h1><p>2026 年 9 月 29 日 · 北京时间</p></div><div className="report-summary"><b>今日判断</b><p>{report.headline}</p><div><span>{report.papers.length} 篇入选</span><span>{full} 篇全文精读</span><span>正式期刊 {formal} 篇</span></div></div></div>
 <div className="report-layout"><aside className="report-toc"><p>本期目录</p>{report.papers.map((p,i)=><a key={p.title} href={'#paper-'+(i+1)}>{String(i+1).padStart(2,'0')} · {p.material.slice(0,16)}</a>)}<a href="#compare">汇总统计</a><a href="#search-log">检索日志</a></aside><article className="report-content">
 <section className="report-lede"><p className="eyebrow">TODAY&apos;S SIGNAL</p><h2>今日要点与访问边界</h2><p>{report.hotspot}</p><ol><li><b>官方新稿：</b>arXiv cond-mat/new 9 月 29 日列出 134 篇 new submissions，已逐条筛标题与摘要。</li><li><b>正式期刊：</b>以 DOI 正式版为主条目；两篇可读合法作者公开稿，期刊排版差异仍待核对。</li><li><b>阅读分级：</b>仅实际读到正文、Methods 和关键图注的 {full} 篇标为全文精读，其余逐篇列为摘要级与补读清单。</li><li><b>访问边界：</b>本期未建立浙江大学已认证机构会话，未上传或附带受订阅限制的 PDF/图片。</li></ol></section>
 {report.papers.map((p,i)=>{const fig=figures[p.title];return <section className="paper-detail" id={'paper-'+(i+1)} key={p.title}><div className="paper-kicker"><span>{String(i+1).padStart(2,'0')} · {p.category}</span><b>{p.access.includes('全文精读')?'全文精读':'摘要级'} · 推荐 {p.rating}</b></div><h2>{p.material}｜{p.title}</h2><div className="tag-row">{p.tags.map(t=><span key={t}>{t}</span>)}</div><div className="meta-grid"><div className="meta-item"><span>来源</span><b>{p.journal}</b></div><div className="meta-item"><span>日期</span><b>{p.date}</b></div><div className="meta-item"><span>生长 / 方法</span><b>{p.method}</b></div><div className="meta-item"><span>作者</span><b>{p.authors}</b></div><div className="meta-item institution-item"><span>主要单位</span><b>{p.institutions}</b></div></div><p className="links"><a href={p.doi}>DOI / arXiv ↗</a>{p.fullText&&p.fullText!==p.doi&&<a href={p.fullText}> 公开全文 ↗</a>}</p><p className="version-note"><b>版本与阅读范围：</b>{p.versionNote} {p.access}</p><div className="paper-conclusion"><span>CONCLUSION</span><h3>这篇论文讲了什么故事</h3><p>{p.conclusion}</p></div>{fig&&<figure className="data-figure"><figcaption><b>{fig.title}</b><span>根据公开正文数值重绘，并非论文原图</span></figcaption><img className="report-figure-image" src={fig.src} alt={fig.title}/><p className="figure-analysis"><b>图解分析：</b>{fig.caption}</p></figure>}{p.sections.map(s=><div key={s.title}><h3>{s.title}</h3>{s.text.split('\n\n').map((part,j)=><p key={j}>{part}</p>)}</div>)}<div className="reading-guide"><span>{p.readingGuide.priority}</span><h3>本篇专属阅读路径</h3><p><b>先读：</b>{p.readingGuide.first}</p><p><b>重点：</b>{p.readingGuide.focus}</p><p><b>下一步：</b>{p.readingGuide.next}</p></div></section>})}
 <section className="comparison" id="compare"><p className="eyebrow">TODAY AT A GLANCE</p><h2>材料、方法与证据状态</h2><div className="table-wrap"><table><thead><tr><th>材料</th><th>方法</th><th>核心物性/问题</th><th>全文状态</th><th>推荐</th></tr></thead><tbody>{report.papers.map(p=><tr key={p.title}><td>{p.material}</td><td>{p.method}</td><td>{p.conclusion.slice(0,72)}…</td><td>{p.access.includes('全文精读')?'全文精读':'摘要级'}</td><td>{p.rating}</td></tr>)}</tbody></table></div><h3>板块统计</h3><p>{Object.entries(counts).map(([k,v])=>`${k} ${v}篇`).join('；')}。正式期刊{formal}篇，arXiv独立稿{report.papers.length-formal}篇；全文精读{full}篇，摘要级{report.papers.length-full}篇。</p></section>
 <section className="search-note" id="search-log"><p className="eyebrow">SEARCH LOG</p><h2>逐轨检索、访问与去重记录</h2><p><b>实际时间窗：</b>{report.searchWindow}</p>{report.searchTerms.map(x=><p key={x}>{x}</p>)}</section></article></div></main>;
}


