/* eslint-disable @next/next/no-html-link-for-pages, @next/next/no-img-element */
import type { Metadata } from 'next';
import report from '../../../content/reports/2026-09-14.json';

export const metadata: Metadata={title:'2026-09-14 简报｜每日文献简报',description:report.headline};
const ids=report.papers.map((_,i)=>`paper-${i+1}`);

function EvidenceFigures(){return <section id="figures">
 <figure className="data-figure"><figcaption><b>原创图解 1｜TiTe₂：生长—暴露—结构/电子相变</b><span>根据arXiv:2609.11992的Sample Growth与图2–7信息原创重绘，并非论文原图</span></figcaption><img className="report-figure-image" src="/reports/2026-09-14/tite2-evidence-chain.svg" alt="TiTe2高压CVT与两条相变证据链"/><p className="figure-analysis"><b>图解分析：</b>左侧是可复现的封管循环：Ti/Te装料、N₂回填、900–1000 °C保温5 d并重复3–5次。右侧刻意分开空气和电子束两条路径：空气证据来自表面STM/STS与XPS，电子束证据来自190 keV TEM/SAED；前者不能直接证明体相半导体化，后者也不能当作平衡热力学相变。</p></figure>
 <figure className="data-figure dark-data"><figcaption><b>原创图解 2｜三类超导问题：正常态、重电子与手性边缘</b><span>根据arXiv:2609.12351、2609.13049、2609.13070的主文证据原创重绘，并非论文原图</span></figcaption><img className="report-figure-image" src="/reports/2026-09-14/superconductivity-evidence-map.svg" alt="Rh基硫化物、三层镍酸盐和扭转BSCCO证据地图"/><p className="figure-analysis"><b>图解分析：</b>三项工作回答不同层级的问题：Rh₁₇₋ₓFeₓS₁₅用比热、Kondo样输运和DAC给出重电子/再入超导链；三层镍酸盐用角度缩放证明二维弱局域化但压力只到3 GPa；扭转BSCCO用NV弛豫把边缘磁噪声空间成像，手性拓扑仍需相位或热输运互证。不能把三个‘超导相关’结果混成同一机制。</p></figure>
 <p className="version-note"><b>图片来源与许可：</b>两张SVG均为本站依据公开Methods与量化结果原创绘制，没有复制论文图形表达；付费正文未取得的三篇论文没有配图。</p>
 </section>}

export default function Report(){const full=report.papers.filter(p=>p.access.includes('全文精读')).length;return <main className="report-page"><header className="site-header"><a className="brand" href="/"><span className="brand-mark">文</span><span>每日文献简报</span></a><nav><a className="active" href="/reports/2026-09-14">今日简报</a><a href="/#topics">研究板块</a><a href="/archive">往期归档</a><a href="/search">智能检索</a></nav><div className="live-chip"><span/> 每日 08:00 更新</div></header>
 <div className="report-hero"><div><p className="eyebrow">DAILY REPORT · ISSUE 020</p><h1>每日文献简报</h1><p>2026 年 9 月 14 日 · 北京时间</p></div><div className="report-summary"><b>今日判断</b><p>{report.headline}</p><div><span>{report.papers.length} 篇入选</span><span>{full} 篇全文精读</span><span>4 个主板块</span></div></div></div>
 <div className="report-layout"><aside className="report-toc"><p>本期目录</p>{report.papers.map((p,i)=><a key={p.title} href={`#${ids[i]}`}>{String(i+1).padStart(2,'0')} · {p.material}</a>)}<a href="#figures">原创图解</a><a href="#compare">横向对比</a><a href="#search-log">检索日志</a></aside><article className="report-content">
  <section className="report-lede"><p className="eyebrow">TODAY&apos;S SIGNAL</p><h2>今日要点与阅读边界</h2><p>{report.hotspot}</p><ol><li><b>当天优先。</b>arXiv采用9月14日官方新稿；正式期刊不足时回溯9月12—14日。</li><li><b>不限制篇数。</b>只要与生长、物性、超导、重费米子、磁性或二维量子材料高度相关即纳入。</li><li><b>全文分级。</b>13篇实际读取全文；3篇Wiley/ACS条目因自动访问403仅保留元数据。</li><li><b>证据边界。</b>未知配方与性能不按常见做法补写，预印本结论与正式同行评议分开标记。</li></ol></section>
  <EvidenceFigures/>
  {report.papers.map((p,i)=><section className="paper-detail" id={ids[i]} key={p.title}><div className="paper-kicker"><span>{String(i+1).padStart(2,'0')} · {p.category}</span><b>{p.access.includes('全文精读')?'全文精读':'摘要/元数据'} · 推荐 {p.rating}</b></div><h2>{p.material}｜{p.title}</h2><div className="tag-row">{p.tags.map(t=><span key={t}>{t}</span>)}</div><div className="meta-grid"><div className="meta-item"><span>来源</span><b>{p.journal}</b></div><div className="meta-item"><span>日期</span><b>{p.date}</b></div><div className="meta-item"><span>生长 / 方法</span><b>{p.method}</b></div><div className="meta-item"><span>作者</span><b>{p.authors}</b></div><div className="meta-item institution-item"><span>主要单位</span><b>{p.institutions}</b></div></div><p className="links"><a href={p.doi}>DOI / 出版社 ↗</a>{p.fullText&&<a href={p.fullText}>全文来源 ↗</a>}</p><p className="version-note"><b>版本与阅读范围：</b>{p.versionNote} {p.access}</p><div className="paper-conclusion"><span>CONCLUSION</span><h3>这篇论文讲了什么故事</h3><p>{p.conclusion}</p></div>{p.sections.map(s=><div key={s.title}><h3>{s.title}</h3><p>{s.text}</p></div>)}<div className="reading-guide"><span>{p.readingGuide.priority}</span><h3>本篇专属阅读路径</h3><p><b>先读：</b>{p.readingGuide.first}</p><p><b>重点：</b>{p.readingGuide.focus}</p><p><b>下一步：</b>{p.readingGuide.next}</p></div></section>)}
  <section className="comparison" id="compare"><p className="eyebrow">COMPARISON</p><h2>本期横向对比</h2><div className="table-wrap"><table><thead><tr><th>板块</th><th>材料</th><th>生长 / 方法</th><th>故事结论</th><th>推荐</th></tr></thead><tbody>{report.papers.map(p=><tr key={p.title}><td>{p.category}</td><td>{p.material}</td><td>{p.method}</td><td>{p.conclusion.slice(0,72)}…</td><td>{p.rating}</td></tr>)}</tbody></table></div></section>
  <section className="search-note" id="search-log"><p className="eyebrow">SEARCH LOG</p><h2>检索、访问与去重记录</h2><p><b>时间窗：</b>{report.searchWindow}</p>{report.searchTerms.map(x=><p key={x}>{x}</p>)}<p><b>全文状态：</b>13篇完成公开全文阅读；Advanced Functional Materials、Advanced Materials与JACS三篇仅元数据级。机构订阅正文未自动取得，也未用经验补写。</p></section>
 </article></div></main>}
