/* eslint-disable @next/next/no-html-link-for-pages */
import type { Metadata } from 'next';
import report from '../../../content/reports/2026-08-31.json';

export const metadata: Metadata = {title:'2026-08-31 简报｜晶体生长和物性调控',description:'YbNi₄P₂ 高场费米面、La₃Ni₂O₇ 位点 NMR 与 MoS₂ 液相前驱体 CVD。'};
const ids=['ybnip','la327','mos2'];
const labels=['YbNi₄P₂','La₃Ni₂O₇','MoS₂'];

function EvidenceFigure({index}:{index:number}){
  if(index===0)return <div className="figure-block dark"><div className="node-figure"><div className="frequency-lines"><span/><span/></div><div className="node-ring"><i/><i/><i/><i/></div></div><p><b>图解 1｜YbNi₄P₂ 的两阶段高场响应。</b>根据正文图 2–5 原创概念重绘，并非论文原图。6–17 T 质量连续减小；B₉≈17 T 时 γ、δ 频率消失并分别裂成两支，说明连续 Kondo 退重整化之外还有突发电子结构变化。</p></div>;
  if(index===1)return <div className="figure-block"><div className="cvt-figure"><div className="ampoule"><span className="source-zone">O(3,4)<small>面内 SDW · Hint≈0.05 T</small></span><i>dₓ²−y² ↔ d₃z²−r²</i><span className="growth-zone">O(2)<small>极小 Knight shift</small></span></div><div className="time-line"><span>TSDW=150 K</span><b>TA≈115 K 层间重排</b><span>轨道选择性</span></div></div><p><b>图解 2｜双层镍酸盐的位点证据链。</b>根据论文信息原创重绘，并非论文原图。面内氧展宽约束条纹 SDW，外顶角氧的极小位移支持 d₃z²−r² 层间单态，内顶角氧在 115 K 以下失去窄峰指向层间取向改变。</p></div>;
  return <div className="figure-block"><div className="cvt-figure"><div className="ampoule"><span className="source-zone">Zone 1<small>S 100 mg · 170 °C</small></span><i>Ar 500 sccm →</i><span className="growth-zone">Zone 2<small>MoO₃/基底 · 750 °C</small></span></div><div className="time-line"><span>旋涂 + 300 °C/30 min</span><b>硫化 30 min</b><span>Zone 3 · 250 °C</span></div></div><p><b>图解 3｜MoS₂ 三温区液相前驱体 CVD。</b>根据 Methods 原创重绘，并非论文原图。Mo 源预先固定在基底，气相只输运 S，从而把随机双源输运转化为基底控制的润湿—反应—扩散问题。</p></div>;
}

export default function Report(){return <main className="report-page">
  <header className="site-header"><a className="brand" href="/"><span className="brand-mark">晶</span><span>晶体生长和物性调控</span></a><nav><a className="active" href="/reports/2026-08-31">今日简报</a><a href="/archive">往期归档</a><a href="/search">文献检索</a></nav><div className="live-chip"><span/> 每日 08:00 更新</div></header>
  <div className="report-hero"><div><p className="eyebrow">DAILY REPORT · ISSUE 006</p><h1>晶体生长与物性<br/>文献简报</h1><p>2026 年 8 月 31 日 · 北京时间</p></div><div className="report-summary"><b>今日判断</b><p>{report.hotspot}</p><div><span>3 篇入选</span><span>3 篇全文精读</span><span>0 篇重复</span></div></div></div>
  <div className="report-layout"><aside className="report-toc"><p>本期目录</p>{ids.map((id,i)=><a key={id} href={`#${id}`}>0{i+1} · {labels[i]}</a>)}<a href="#compare">汇总对比</a><a href="#search">检索记录</a></aside><article className="report-content">
    <section className="report-lede"><p className="eyebrow">TODAY&apos;S SIGNAL</p><h2>今日要点</h2><ol><li><b>YbNi₄P₂ 的关键是把连续与突发分开。</b>有效质量随场先连续减半，17 T 附近频率再成对突变；g 因子突变和费米面重构仍需新探针区分。</li><li><b>La₃Ni₂O₇ 是多晶局域物性条目。</b>¹⁷O 位点选择性谱同时约束面内条纹、层间单态和 115 K 自旋重排，但不能被误写成单晶生长成果。</li><li><b>MoS₂ 给出本期最可复现的工艺卡。</b>旋涂、煅烧、三温区与气流参数齐全；“反应—扩散机制”仍是 ex situ 相关性，尚非原位定量证明。</li></ol></section>
    {report.papers.map((paper,index)=><section className="paper-detail" id={ids[index]} key={paper.title}><div className="paper-kicker"><span>0{index+1}</span><b>{paper.access} · 推荐 {paper.rating}</b></div><h2>{paper.material}：{paper.title}</h2><p className="english-title">{paper.title}</p><div className="meta-grid"><div className="meta-item"><span>来源</span><b>{paper.journal}</b></div><div className="meta-item"><span>日期</span><b>{paper.date}</b></div><div className="meta-item"><span>生长</span><b>{paper.method}</b></div><div className="meta-item"><span>作者</span><b>{paper.authors}</b></div></div><p className="links"><a href={paper.doi}>arXiv 条目 ↗</a><a href={paper.fullText}>HTML 全文 ↗</a></p>{paper.sections.map((section,sectionIndex)=><div key={section.title}><h3>{section.title}</h3><p>{section.text}</p>{sectionIndex===1&&<EvidenceFigure index={index}/>}</div>)}</section>)}
    <section className="comparison" id="compare"><p className="eyebrow">COMPARISON</p><h2>本期汇总</h2><div className="table-wrap"><table><thead><tr><th>材料 / 样品</th><th>生长</th><th>关键窗口</th><th>主要物性与核心数据</th><th>推荐</th></tr></thead><tbody><tr><td>YbNi₄P₂<br/>四方定向单晶</td><td>Czochralski</td><td>0.3 K；6–35 T；B₉≈17 T</td><td>m* 7→3.2mₑ；频率裂分 20–30%</td><td>重费米高场 · S</td></tr><tr><td>La₃Ni₂O₇₊δ<br/>¹⁷O 粗多晶粉</td><td>固相 + 1000 °C/4 h 同位素交换</td><td>11.968 T；20–160 K</td><td>TSDW=150 K；TA≈115 K；Hint≈0.05 T</td><td>轨道选择性 · A+</td></tr><tr><td>MoS₂/晶体基底<br/>单层/少层畴</td><td>液相前驱体 CVD</td><td>S 170 °C；生长 750 °C/30 min；Ar 500 sccm</td><td>15–49% 单层覆盖；形貌/PL 基底可调</td><td>可复现生长 · S</td></tr></tbody></table></div></section>
    <section className="search-note" id="search"><p className="eyebrow">SEARCH LOG</p><h2>检索、全文访问与去重</h2><p><b>实际时间窗：</b>{report.searchWindow}</p><p><b>检索词：</b>{report.searchTerms.join('；')}。</p><p><b>数据库/站点：</b>arXiv cond-mat/new、arXiv abstract 与 HTML 全文，并检索 APS/Nature 关键词页。三篇均实际读取正文与方法/补充部分，全文状态已逐篇注明。按 arXiv ID、题目及往期 JSON 比对，重复 0 篇；没有用最近三天之外的论文凑数。</p><p><b>访问与图片：</b>本期采用三张根据论文信息原创的网页示意，均非论文原图；原文 HTML 为可点击的一手来源。检索时间：2026-08-31（北京时间）。</p></section>
  </article></div>
</main>}
