/* eslint-disable @next/next/no-html-link-for-pages, @next/next/no-img-element */
import type {Metadata} from 'next';
import report from '../../../content/reports/2026-09-18.json';

export const metadata:Metadata={title:'2026-09-18 简报｜每日文献简报',description:report.headline};

const figures:Record<string,{src:string;title:string;caption:string}>= {
  'Encapsulation epitaxy of air-stable monolayer superconducting films for quantum circuits and qubits':{src:'/reports/2026-09-18/nbse2-growth.svg',title:'原创图解 1｜封装外延NbSe₂关键温程',caption:'依据arXiv:2609.19321 Methods数值重绘，并非原始温度记录或论文原图。15 min升至950 °C、9 min保温、随后快速冷却；NaCl在上游约750–850 °C。源与基底相距1–3 mm。来源：https://arxiv.org/abs/2609.19321 。'},
  'Superconductivity at the metal-insulator phase boundary in a bulk nickelate at ambient pressure':{src:'/reports/2026-09-18/nickelate-fraction.svg',title:'原创图解 2｜镍酸盐转变温度与体积分数不能混读',caption:'依据arXiv:2609.19686正文数值重绘，并非论文原图。Pr样Tc约7 K、估计超导体积分数约2%；Y样Tc约15 K、约0.03%。并列列出体积分数，条长不代表线性或对数比例，绝不能把电阻下降直接等同均匀块体超导。来源：https://arxiv.org/abs/2609.19686 。'},
  'Crystallographic imperfections and exotic superconductivity of UBe13':{src:'/reports/2026-09-18/ube13-defects.svg',title:'原创图解 3｜UBe₁₃微小结构变化与Tc变化',caption:'据arXiv:2609.19678正文报告的约0.006%晶胞体积变化、约28% Tc变化绘制概念比例。不是实测点列或因果拟合；提醒比较Al Flux样与无Al样时同时测占位、空位和退火史。来源：https://arxiv.org/abs/2609.19678 。'}
};

export default function Report(){
 const full=report.papers.filter(p=>p.access.includes('全文精读')).length;
 const counts=report.papers.reduce<Record<string,number>>((m,p)=>(m[p.category]=(m[p.category]||0)+1,m),{});
 return <main className="report-page">
 <header className="site-header"><a className="brand" href="/"><span className="brand-mark">文</span><span>每日文献简报</span></a><nav aria-label="主导航"><a className="active" href="/reports/2026-09-18">今日简报</a><a href="/materials">材料时间线</a><a href="/search">智能检索</a><a href="/weekly">本周趋势</a><a href="/workspace">我的研究</a><a href="/archive">归档</a></nav><div className="live-chip"><span/> 每日 10:00 更新</div></header>
 <div className="report-hero"><div><p className="eyebrow">DAILY REPORT · ISSUE 024</p><h1>每日文献简报</h1><p>2026 年 9 月 17 日 · 北京时间</p></div><div className="report-summary"><b>今日判断</b><p>{report.headline}</p><div><span>{report.papers.length} 篇入选</span><span>{full} 篇全文精读</span><span>正式期刊 3 篇</span></div></div></div>
 <div className="report-layout"><aside className="report-toc"><p>本期目录</p>{report.papers.map((p,i)=><a key={p.title} href={'#paper-'+(i+1)}>{String(i+1).padStart(2,'0')} · {p.material.slice(0,14)}</a>)}<a href="#compare">板块统计</a><a href="#search-log">检索日志</a></aside><article className="report-content">
 <section className="report-lede"><p className="eyebrow">TODAY&apos;S SIGNAL</p><h2>今日要点与访问边界</h2><p>{report.hotspot}</p><ol><li><b>正式期刊与预印本：</b>正式期刊3篇，arXiv当天公告9篇；按样品、生长、缺陷与物性证据链筛选。</li><li><b>阅读等级：</b>3篇公开PDF全文精读、6篇PDF正文核查、3篇仅基于摘要；正文受限的不补写实验细节。</li><li><b>实验优先：</b>封装外延NbSe₂、常压镍酸盐和UBe₁₃缺陷依赖最值得先读；镍酸盐的低体积分数需要特别谨慎。</li><li><b>图解合规：</b>三张图由本站按公开数值原创重绘，不复用论文原图。</li></ol></section>
 {report.papers.map((p,i)=>{const fig=figures[p.title];return <section className="paper-detail" id={'paper-'+(i+1)} key={p.title}><div className="paper-kicker"><span>{String(i+1).padStart(2,'0')} · {p.category}</span><b>{p.access.includes('全文精读')?'全文精读':p.access.includes('正文核查')?'正文核查':'摘要级'} · 推荐 {p.rating}</b></div><h2>{p.material}｜{p.title}</h2><div className="tag-row">{p.tags.map(t=><span key={t}>{t}</span>)}</div><div className="meta-grid"><div className="meta-item"><span>来源</span><b>{p.journal}</b></div><div className="meta-item"><span>上线日期</span><b>{p.date}</b></div><div className="meta-item"><span>生长 / 方法</span><b>{p.method}</b></div><div className="meta-item"><span>作者</span><b>{p.authors}</b></div><div className="meta-item institution-item"><span>主要单位</span><b>{p.institutions}</b></div></div><p className="links"><a href={p.doi}>DOI / 原文 ↗</a>{p.fullText&&<a href={p.fullText}> 公开全文 ↗</a>}</p><p className="version-note"><b>版本与阅读范围：</b>{p.versionNote} {p.access}</p><div className="paper-conclusion"><span>CONCLUSION</span><h3>这篇论文讲了什么故事</h3><p>{p.conclusion}</p></div>{fig&&<figure className="data-figure"><figcaption><b>{fig.title}</b><span>根据公开Methods与正文数值重绘，并非论文原图</span></figcaption><img className="report-figure-image" src={fig.src} alt={fig.title}/><p className="figure-analysis"><b>图解分析：</b>{fig.caption}</p></figure>}{p.sections.map(s=><div key={s.title}><h3>{s.title}</h3>{s.text.split('\n\n').map((part,j)=><p key={j}>{part}</p>)}</div>)}<div className="reading-guide"><span>{p.readingGuide.priority}</span><h3>本篇专属阅读路径</h3><p><b>先读：</b>{p.readingGuide.first}</p><p><b>重点：</b>{p.readingGuide.focus}</p><p><b>下一步：</b>{p.readingGuide.next}</p></div></section>})}
 <section className="comparison" id="compare"><p className="eyebrow">TODAY AT A GLANCE</p><h2>板块与全文状态</h2><div className="table-wrap"><table><thead><tr><th>研究板块</th><th>篇数</th></tr></thead><tbody>{Object.entries(counts).map(([k,v])=><tr key={k}><td>{k}</td><td>{v}</td></tr>)}</tbody></table></div><p>正式期刊3篇；arXiv当天公告9篇；全文精读3篇；正文核查6篇；仅摘要3篇。各篇生长方法、关键物性与推荐等级见上方分篇标题和结论。</p></section>
 <section className="search-note" id="search-log"><p className="eyebrow">SEARCH LOG</p><h2>逐轨检索、访问与去重记录</h2><p><b>时间窗：</b>{report.searchWindow}</p>{report.searchTerms.map(x=><p key={x}>{x}</p>)}</section>
 </article></div></main>;
}
